In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('JD_climate.csv')
b=pd.read_csv('JD_Soil.csv')
c=pd.read_csv('JD_groundwater.csv')
d=pd.read_csv('JD_Fertilizers.csv')
e=pd.read_csv('JD_Pesticides.csv')
f=pd.read_csv('JD_Crop_data.csv')

In [3]:
climate=pd.DataFrame(a['Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,12977,4.0,1.48,200,1746,1524
1,13527,5.1,1.47,201,1567,1524
2,14670,5.2,1.47,202,1568,1524
3,13855,4.5,1.47,203,1569,1524
4,14075,5.1,1.47,204,1570,1524
5,11712,5.5,1.47,205,1571,1524
6,14731,4.5,1.47,206,1572,1524
7,12077,5.1,1.47,207,1746,1524
8,12270,5.5,1.47,208,1747,1524
9,16047,4.5,1.47,209,1748,1524
10,14297,5.1,1.47,210,1749,1524
11,10844,5.5,1.47,211,1750,1524
12,15342,5.1,1.47,212,1751,1524
13,12906,5.2,1.47,213,1752,1524
14,16503,4.5,1.47,214,1753,1524
15,16805,5.1,1.47,215,1754,1524
16,16507,5.5,1.47,216,1755,1524
17,14747,4.5,1.47,217,1756,1524
18,12882,5.1,1.47,218,1757,1524
19,15296,5.5,1.48,219,1758,1524
20,12797,4.5,1.48,220,1759,1524
21,14268,5.5,1.48,221,1760,1524
22,14262,4.5,1.48,222,1761,1524
23,13967,5.1,1.48,223,1762,1524
24,12740,5.5,1.48,224,1763,1524
25,13732,4.5,1.48,225,1764,1524
26,14803,5.1,1.48,226,1765,1524
27,10291,5.5,1.48,227,1766,1524
28,10608,5.1,1.48,228,1767,1524
29,15506,5.2,1.48,229,1768,1524
...,...,...,...,...,...,...
71,13432,5.5,1.48,271,1810,1524
72,14524,4.5,1.48,272,1811,1524
73,11093,5.5,1.48,273,1812,1524
74,14493,4.5,1.48,274,1813,1524
75,11697,5.1,1.48,275,1814,1524
76,14581,5.5,1.48,276,1815,1524
77,15614,4.5,1.48,277,1816,1524
78,11967,5.1,1.48,278,1817,1524
79,14988,5.5,1.48,279,1818,1524
80,14574,5.1,1.48,280,1819,1524
81,16724,5.2,1.48,281,1820,1524
82,11717,4.5,1.48,282,1821,1524
83,8559,5.1,1.48,283,1822,1524
84,12630,5.5,1.48,284,1823,1524
85,11027,4.5,1.48,285,1824,1524
86,13087,5.1,1.48,286,1825,1524
87,10910,5.5,1.48,287,1826,1524
88,11244,4.5,1.48,288,1827,1524
89,12958,5.1,1.48,289,1828,1524
90,11403,5.5,1.48,290,1829,1524
91,12892,4.5,1.48,291,1830,1524
92,13834,5.1,1.48,292,1831,1524
93,17187,5.5,1.48,293,1832,1524
94,15556,5.1,1.48,294,1833,1524
95,9488,5.2,1.48,295,1834,1524
96,12727,4.5,1.48,296,1835,1524
97,11899,5.1,1.48,297,1836,1524
98,11161,5.5,1.48,298,1837,1524
99,12687,4.5,1.48,299,1838,1524
100,13853,5.1,1.48,300,1839,1524

In [11]:
#################AdaBoost Classifier Algorithm##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
a=RandomForestClassifier()

In [17]:
a=a.fit(X_train,y_train)

In [18]:
print(a.score(X_test,y_test)*10)

10.0

In [19]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Tur', 'Gram',
       'Groundnuts', 'Sessasum', 'Sugarcane', 'Bajra', 'Maize', 'Potato',
       'Wheat', 'Other Pulses'],
      dtype='object')

In [20]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Tur'])
Crop5=pd.DataFrame(f['Gram'])
Crop6=pd.DataFrame(f['Groundnuts'])
Crop7=pd.DataFrame(f['Sessasum'])
Crop8=pd.DataFrame(f['Sugarcane'])
Crop9=pd.DataFrame(f['Bajra'])
Crop10=pd.DataFrame(f['Maize'])
Crop11=pd.DataFrame(f['Potato'])
Crop12=pd.DataFrame(f['Wheat'])
Crop13=pd.DataFrame(f['Other Pulses'])

In [21]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)

In [22]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Tur',axis=1)
y3=Parameteronec['Tur']

X4=Parameteroned.drop('Gram',axis=1)
y4=Parameteroned['Gram']

X5=Parameteronee.drop('Groundnuts',axis=1)
y5=Parameteronee['Groundnuts']

X6=Parameteronef.drop('Sessasum',axis=1)
y6=Parameteronef['Sessasum']

X7=Parameteroneg.drop('Sugarcane',axis=1)
y7=Parameteroneg['Sugarcane']

X8=Parameteroneh.drop('Bajra',axis=1)
y8=Parameteroneh['Bajra']

X9=Parameteronei.drop('Maize',axis=1)
y9=Parameteronei['Maize']

X10=Parameteronej.drop('Potato',axis=1)
y10=Parameteronej['Potato']

X11=Parameteronek.drop('Wheat',axis=1)
y11=Parameteronek['Wheat']

X12=Parameteronel.drop('Other Pulses',axis=1)
y12=Parameteronel['Other Pulses']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
b=RandomForestClassifier()
c=RandomForestClassifier()
d=RandomForestClassifier()
e=RandomForestClassifier()
f=RandomForestClassifier()
g=RandomForestClassifier()
h=RandomForestClassifier()
i=RandomForestClassifier()
j=RandomForestClassifier()
k=RandomForestClassifier()
l=RandomForestClassifier()
m=RandomForestClassifier()

In [27]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [28]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))

0.14084507042253522
0.14084507042253522
0.14084507042253522
0.14084507042253522
0.14084507042253522
0.014084507042253521
0.14084507042253522
0.014084507042253521
0.14084507042253522
0.14084507042253522
0.014084507042253521
0.014084507042253521