In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('climate Test1.csv')
b=pd.read_csv('Soil Test1.csv')
c=pd.read_csv('groundwater Test1.csv')
d=pd.read_csv('Fertilizers Test1.csv')
e=pd.read_csv('Pesticides Test1.csv')
f=pd.read_csv('Crop data Test1.csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,11093,8.2,0.1,2400,1950,2220
1,4891,6.6,0.1,2401,2100,1902
2,8299,6.7,0.1,2300,1900,2109
3,10250,6.8,0.1,2365,1902,1890
4,14001,6.9,0.1,2400,1950,2013
5,9271,7.0,0.1,2401,1680,2100
6,14002,7.1,0.1,2300,2000,1890
7,6350,7.2,0.1,2365,1900,2013
8,11702,7.3,0.1,2400,1902,2100
9,14983,7.4,0.1,2401,1950,2220
10,6725,7.8,0.1,2300,1900,2103
11,9875,8.0,0.1,2365,1902,2220
12,6543,8.1,0.1,2400,1950,1902
13,10931,8.2,0.1,2401,1680,2109
14,10109,8.3,0.1,2300,2000,1890
15,6406,8.5,0.1,2365,1900,2013
16,6898,6.5,0.1,2400,1902,2100
17,9719,6.6,0.1,2300,1950,2109
18,5637,6.7,0.1,2365,2100,1090
19,6351,6.8,0.1,2400,1900,2013
20,12011,6.9,0.1,2401,1902,2100
21,7738,7.0,0.1,2300,1950,2220
22,4387,7.1,0.1,2365,1680,2103
23,11012,7.2,0.1,2400,2000,2220
24,3934,7.3,0.1,2401,1900,1902
25,12011,7.4,0.1,2300,1902,2109
26,12457,7.8,0.1,2365,1950,1890
27,11046,8.5,0.1,2400,2100,2013
28,8475,6.5,0.1,2401,2000,2100
29,8323,6.6,0.1,2300,1900,1890
30,8003,6.7,0.1,2365,1902,2013

In [13]:
#################AdaBoost Classifier Algorithm##################

X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

from sklearn.neural_network import MLPClassifier

a=MLPClassifier()

a=a.fit(X_train,y_train)

print(a.score(X_test,y_test)*10)

Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur '])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Tobacco'])
Crop12=pd.DataFrame(f['Coconut'])
Crop13=pd.DataFrame(f['Bajra'])
Crop14=pd.DataFrame(f['Maize'])
Crop15=pd.DataFrame(f['Cotton'])
Crop16=pd.DataFrame(f['Potato'])
Crop17=pd.DataFrame(f['Wheat'])
Crop18=pd.DataFrame(f['Other Pulses'])

Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)


X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur ',axis=1)
y4=Parameteroned['Tur ']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Tobacco',axis=1)
y10=Parameteronej['Tobacco']

X11=Parameteronek.drop('Coconut',axis=1)
y11=Parameteronek['Coconut']

X12=Parameteronel.drop('Bajra',axis=1)
y12=Parameteronel['Bajra']

X13=Parameteronem.drop('Maize',axis=1)
y13=Parameteronem['Maize']

X14=Parameteronen.drop('Cotton',axis=1)
y14=Parameteronen['Cotton']

X15=Parameteroneo.drop('Potato',axis=1)
y15=Parameteroneo['Potato']

X16=Parameteronep.drop('Wheat',axis=1)
y16=Parameteronep['Wheat']

X17=Parameteroneq.drop('Other Pulses',axis=1)
y17=Parameteroneq['Other Pulses']

from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)



from sklearn.neural_network import MLPClassifier


b=MLPClassifier()
c=MLPClassifier()
d=MLPClassifier()
e=MLPClassifier()
f=MLPClassifier()
g=MLPClassifier()
h=MLPClassifier()
i=MLPClassifier()
j=MLPClassifier()
k=MLPClassifier()
l=MLPClassifier()
m=MLPClassifier()
n=MLPClassifier()
o=MLPClassifier()
p=MLPClassifier()
q=MLPClassifier()
r=MLPClassifier()


b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)


print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)

0.4545454545454546
3.1818181818181817
2.727272727272727
4.545454545454545
3.1818181818181817
3.1818181818181817
0.3181818181818182
3.1818181818181817
0.3181818181818182
3.1818181818181817
3.1818181818181817
0.3181818181818182
0.3181818181818182
0.3181818181818182
10.0
3.1818181818181817
0.3181818181818182
3.1818181818181817