In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('climate Test1.csv')
b=pd.read_csv('Soil Test1.csv')
c=pd.read_csv('groundwater Test1.csv')
d=pd.read_csv('Fertilizers Test1.csv')
e=pd.read_csv('Pesticides Test1.csv')
f=pd.read_csv('Crop data Test1.csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,37032,6.6,0.01,1922,662,2341
1,32689,7.5,0.01,1923,663,2342
2,27230,6.5,0.01,1924,664,2765
3,32410,7.0,0.01,1925,665,2712
4,31400,6.8,0.01,1926,666,2613
5,40299,6.9,0.01,1927,667,2432
6,35317,7.1,0.01,1928,668,2433
7,29901,7.2,0.01,1919,669,2434
8,33366,7.3,0.01,1920,670,2435
9,37498,7.4,0.01,1921,671,2436
10,32662,7.5,0.01,1915,672,2437
11,55526,6.5,0.01,1916,673,2438
12,37723,7.0,0.01,1917,674,2439
13,30577,6.8,0.01,1918,675,2332
14,31259,6.9,0.01,1919,676,2333
15,26132,7.1,0.01,1920,677,2334
16,27940,7.2,0.01,1921,643,2335
17,30681,7.3,0.01,1922,644,2336
18,32038,7.4,0.01,1923,645,2337
19,28141,6.6,0.01,1924,646,2338
20,43613,7.5,0.01,1925,647,2339
21,34014,6.5,0.01,1926,648,2340
22,25219,7.0,0.01,1927,649,2341
23,32082,6.8,0.01,1928,650,2330
24,37713,6.9,0.01,1919,651,2331
25,50565,7.1,0.01,1920,652,2332
26,28034,7.2,0.01,1921,653,2333
27,34554,7.3,0.01,1922,654,2334
28,41017,7.4,0.01,1923,655,2335
29,27913,6.6,0.01,1923,656,2336
30,34772,7.5,0.01,1916,657,2337

In [11]:
#################Ada Boost Classifier##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
Parameterone.columns

Index([' Rainfall', 'Ph', 'Rise (Depth of Water)', 'NPK(tonnes)',
       'MALATHION(QTY)(kg)', 'Rice(kg/hectare)'],
      dtype='object')

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
a=RandomForestClassifier()

In [18]:
a=a.fit(X_train,y_train)

In [19]:
print(a.score(X_test,y_test)*10)

0.0

In [20]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur ',
       'Gram', 'Groundnuts', 'Sessasum', 'Banana', 'Sugarcane', 'Tobacco',
       'Chillies', 'Ginger', 'Coconut', 'Tumeric', 'Bajra', 'Maize', 'Cotton',
       'Potato', 'Wheat', 'Other Pulses', 'Mesta', 'Pepper', 'Tea'],
      dtype='object')

In [21]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur '])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Tobacco'])
Crop12=pd.DataFrame(f['Chillies'])
Crop13=pd.DataFrame(f['Ginger'])
Crop14=pd.DataFrame(f['Coconut'])
Crop15=pd.DataFrame(f['Tumeric'])
Crop16=pd.DataFrame(f['Bajra'])
Crop17=pd.DataFrame(f['Maize'])
Crop18=pd.DataFrame(f['Cotton'])
Crop19=pd.DataFrame(f['Potato'])
Crop20=pd.DataFrame(f['Wheat'])
Crop21=pd.DataFrame(f['Other Pulses'])
Crop22=pd.DataFrame(f['Mesta'])
Crop23=pd.DataFrame(f['Pepper'])
Crop24=pd.DataFrame(f['Tea'])

In [22]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)
Parameteronet=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop21],axis=1)
Parameteroneu=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop22],axis=1)
Parameteronev=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop23],axis=1)
Parameteronew=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop24],axis=1)

In [23]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur ',axis=1)
y4=Parameteroned['Tur ']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Tobacco',axis=1)
y10=Parameteronej['Tobacco']

X11=Parameteronek.drop('Chillies',axis=1)
y11=Parameteronek['Chillies']

X12=Parameteronel.drop('Ginger',axis=1)
y12=Parameteronel['Ginger']

X13=Parameteronem.drop('Coconut',axis=1)
y13=Parameteronem['Coconut']

X14=Parameteronen.drop('Tumeric',axis=1)
y14=Parameteronen['Tumeric']

X15=Parameteroneo.drop('Bajra',axis=1)
y15=Parameteroneo['Bajra']

X16=Parameteronep.drop('Maize',axis=1)
y16=Parameteronep['Maize']

X17=Parameteroneq.drop('Cotton',axis=1)
y17=Parameteroneq['Cotton']

X18=Parameteroner.drop('Potato',axis=1)
y18=Parameteroner['Potato']

X19=Parameterones.drop('Wheat',axis=1)
y19=Parameterones['Wheat']

X20=Parameteronet.drop('Other Pulses',axis=1)
y20=Parameteronet['Other Pulses']

X21=Parameteroneu.drop('Mesta',axis=1)
y21=Parameteroneu['Mesta']

X22=Parameteronev.drop('Pepper',axis=1)
y22=Parameteronev['Pepper']

X23=Parameteronew.drop('Tea',axis=1)
y23=Parameteronew['Tea']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)
X_train20, X_test20, y_train20, y_test20 = train_test_split(X20, y20, test_size=0.70,random_state=70)
X_train21, X_test21, y_train21, y_test21 = train_test_split(X21, y21, test_size=0.70,random_state=70)
X_train22, X_test22, y_train22, y_test22 = train_test_split(X22, y22, test_size=0.70,random_state=70)
X_train23, X_test23, y_train23, y_test23 = train_test_split(X23, y23, test_size=0.70,random_state=70)

In [26]:
from sklearn.ensemble import RandomForestClassifier


b=RandomForestClassifier()
c=RandomForestClassifier()
d=RandomForestClassifier()
e=RandomForestClassifier()
f=RandomForestClassifier()
g=RandomForestClassifier()
h=RandomForestClassifier()
i=RandomForestClassifier()
j=RandomForestClassifier()
k=RandomForestClassifier()
l=RandomForestClassifier()
m=RandomForestClassifier()
n=RandomForestClassifier()
o=RandomForestClassifier()
p=RandomForestClassifier()
q=RandomForestClassifier()
r=RandomForestClassifier()
s=RandomForestClassifier()
t=RandomForestClassifier()
u=RandomForestClassifier()
v=RandomForestClassifier()
w=RandomForestClassifier()
x=RandomForestClassifier()

In [27]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)
t.fit(X_train19,y_train19)
u.fit(X_train20,y_train20)
v.fit(X_train21,y_train21)
w.fit(X_train22,y_train22)
x.fit(X_train23,y_train23)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [28]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3))
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5))
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15))
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)
print(t.score(X_test19,y_test19)*10)
print(u.score(X_test20,y_test20)*10)
print(v.score(X_test21,y_test21)*10)
print(w.score(X_test22,y_test22)*10)
print(x.score(X_test23,y_test23)*10)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.045454545454545456
0.0
0.0
0.09090909090909091
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.4545454545454546