In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('AR climate.csv')
b=pd.read_csv('AR Soil.csv')
c=pd.read_csv('AR_groundwater.csv')
d=pd.read_csv('AR_Fertilizers.csv')
e=pd.read_csv('AR Pesticides.csv')
f=pd.read_csv('AR Crop data.csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,4678,4.0,0.8,1,1750,1687
1,5000,4.1,1.8,1,1751,1688
2,5001,4.2,2.8,1,1752,1689
3,5002,4.4,3.8,1,1753,1690
4,5003,4.5,4.8,1,1754,1691
5,5004,4.0,5.8,1,1755,1692
6,5005,4.1,6.8,1,1756,1693
7,5006,4.2,7.8,1,1757,1694
8,5007,4.4,8.8,1,1758,1695
9,5008,4.2,9.8,1,1759,1696
10,5009,4.4,10.8,1,1760,1697
11,5010,4.5,11.8,1,1761,1698
12,5011,4.0,12.8,1,1762,1699
13,5012,4.1,13.8,1,1763,1700
14,5013,4.2,14.8,1,1764,1701
15,5014,4.1,15.8,1,1765,1702
16,5015,4.2,16.8,1,1766,1703
17,5016,4.4,17.8,1,1767,1704
18,5017,4.5,18.8,1,1768,1705
19,5018,4.0,19.8,1,1769,1706
20,5019,4.1,20.8,1,1770,1707
21,5020,4.2,21.8,1,1771,1708
22,5021,4.4,22.8,1,1772,1709
23,5022,4.2,23.8,1,1773,1710
24,5023,4.4,24.8,1,1774,1711
25,5024,4.5,25.8,1,1775,1712
26,5025,4.0,26.8,1,1776,1713
27,5026,4.1,27.8,1,1777,1714
28,5027,4.0,28.8,1,1778,1715
29,5028,4.1,29.8,1,1779,1716
...,...,...,...,...,...,...
71,5070,4.5,71.8,1,1821,1758
72,5071,4.0,72.8,1,1822,1759
73,5072,4.1,73.8,1,1823,1760
74,5073,4.0,74.8,1,1824,1761
75,5074,4.1,75.8,1,1825,1762
76,5075,4.2,76.8,1,1826,1763
77,5076,4.4,77.8,1,1827,1764
78,5077,4.5,78.8,1,1828,1765
79,5078,4.0,79.8,1,1829,1766
80,5079,4.1,80.8,1,1830,1767
81,5080,4.2,81.8,1,1831,1768
82,5081,4.4,82.8,1,1832,1769
83,5082,4.2,83.8,1,1833,1770
84,5083,4.4,84.8,1,1834,1771
85,5084,4.5,85.8,1,1835,1772
86,5085,4.2,86.8,1,1836,1773
87,5086,4.4,87.8,1,1837,1774
88,5087,4.5,88.8,1,1838,1775
89,5088,4.0,89.8,1,1839,1776
90,5089,4.1,90.8,1,1840,1876
91,5090,4.2,91.8,1,1841,1987
92,5091,4.4,92.8,1,1842,2056
93,5092,4.2,93.8,1,1843,2123
94,5093,4.4,94.8,1,1844,2124
95,5094,4.5,95.8,1,1845,2125
96,5095,4.0,96.8,1,1846,2126
97,5096,4.1,97.8,1,1847,2127
98,5097,4.2,98.8,1,1848,2128
99,5098,4.1,99.8,1,1849,2129
100,5099,4.2,100.8,1,1850,2130

In [11]:
#################AdaBoost Classifier Algorithm##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [15]:
from sklearn.ensemble import ExtraTreesClassifier

In [16]:
a=ExtraTreesClassifier()

In [17]:
a=a.fit(X_train,y_train)

In [18]:
print(a.score(X_test,y_test)*10)

0.0

In [19]:
Crop2=pd.DataFrame(f['Small Millets'])
Crop3=pd.DataFrame(f['Tur '])
Crop4=pd.DataFrame(f['Sessasum'])
Crop5=pd.DataFrame(f['Banana'])
Crop6=pd.DataFrame(f['Sugarcane'])
Crop7=pd.DataFrame(f['Chillies'])
Crop8=pd.DataFrame(f['Ginger'])
Crop9=pd.DataFrame(f['Tumeric'])
Crop10=pd.DataFrame(f['Maize'])
Crop11=pd.DataFrame(f['Potato'])
Crop12=pd.DataFrame(f['Wheat'])
Crop13=pd.DataFrame(f['Other Pulses'])
Crop14=pd.DataFrame(f['Groundnuts'])

In [20]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)

In [21]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Small Millets', 'Tur ', 'Sessasum',
       'Banana', 'Sugarcane', 'Chillies', 'Ginger', 'Tumeric', 'Maize',
       'Potato', 'Wheat', 'Other Pulses', 'Groundnuts'],
      dtype='object')

In [22]:
X1=Parameteronea.drop('Small Millets',axis=1)
y1=Parameteronea['Small Millets']

X2=Parameteroneb.drop('Tur ',axis=1)
y2=Parameteroneb['Tur ']

X3=Parameteronec.drop('Sessasum',axis=1)
y3=Parameteronec['Sessasum']

X4=Parameteroned.drop('Banana',axis=1)
y4=Parameteroned['Banana']

X5=Parameteronee.drop('Sugarcane',axis=1)
y5=Parameteronee['Sugarcane']

X6=Parameteronef.drop('Chillies',axis=1)
y6=Parameteronef['Chillies']

X7=Parameteroneg.drop('Ginger',axis=1)
y7=Parameteroneg['Ginger']

X8=Parameteroneh.drop('Tumeric',axis=1)
y8=Parameteroneh['Tumeric']

X9=Parameteronei.drop('Maize',axis=1)
y9=Parameteronei['Maize']

X10=Parameteronej.drop('Potato',axis=1)
y10=Parameteronej['Potato']

X11=Parameteronek.drop('Wheat',axis=1)
y11=Parameteronek['Wheat']

X12=Parameteronel.drop('Other Pulses',axis=1)
y12=Parameteronel['Other Pulses']

X13=Parameteronem.drop('Groundnuts',axis=1)
y13=Parameteronem['Groundnuts']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)

In [25]:
from sklearn.ensemble import ExtraTreesClassifier

In [26]:
b=ExtraTreesClassifier()
c=ExtraTreesClassifier()
d=ExtraTreesClassifier()
e=ExtraTreesClassifier()
f=ExtraTreesClassifier()
g=ExtraTreesClassifier()
h=ExtraTreesClassifier()
i=ExtraTreesClassifier()
j=ExtraTreesClassifier()
k=ExtraTreesClassifier()
l=ExtraTreesClassifier()
m=ExtraTreesClassifier()
n=ExtraTreesClassifier()

In [27]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [28]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4))
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))

0.0
0.0
0.0
1.0
0.0
0.28169014084507044
1.8309859154929577
0.2112676056338028
0.0
10.0
0.0
0.0
0.0