In [150]:
import numpy as np
import pandas as pd

In [151]:
a=pd.read_csv('MP_climate.csv')
b=pd.read_csv('MP_Soil.csv')
c=pd.read_csv('MP_groundwater.csv')
d=pd.read_csv('MP_Fertilizers.csv')
e=pd.read_csv('MP_Pesticides.csv')
f=pd.read_csv('MP_Crop_data.csv')

In [152]:
climate=pd.DataFrame(a['Rainfall'])

In [153]:
Soil=pd.DataFrame(b['Ph'])

In [154]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [155]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [156]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [157]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [158]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [159]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,7123,6.5,0.5,1689,2271,1343
1,8086,8.0,0.2,1178,2400,1278
2,9179,6.6,0.5,1578,1980,1409
3,10148,6.7,0.5,1489,1890,1343
4,10125,6.8,0.5,1400,1760,1278
5,7161,7.0,0.5,1178,9000,1409
6,9282,8.0,0.5,1578,7890,1105
7,8651,6.6,0.5,1489,7567,1343
8,8927,6.7,0.5,1178,5672,1278
9,7133,6.8,0.5,1578,2100,1409
10,8834,8.0,0.5,1489,1980,1343
11,11604,6.6,0.5,1400,1890,1278
12,9898,6.7,0.5,1178,1760,1409
13,12444,6.8,0.5,1578,9000,1343
14,11893,7.0,0.5,1178,7890,1278
15,8905,8.0,0.5,1578,7567,1409
16,9233,6.6,0.5,1489,1980,1105
17,10405,6.7,0.5,1400,1890,1343
18,10318,6.6,0.5,1178,1760,1278
19,8598,6.7,0.5,1578,9000,1409
20,10982,6.8,0.5,1489,7890,1343
21,7729,7.0,0.5,1178,7567,1278
22,12106,8.0,0.5,1578,5672,1409
23,9746,6.6,0.5,1489,2100,1105
24,13865,6.7,0.5,1400,1980,1343
25,10393,6.8,0.5,1689,1890,1278
26,12659,8.0,0.5,1178,1760,1409
27,10985,6.6,0.5,1578,9000,1343
28,13033,6.7,0.5,1489,7890,1278
29,9130,6.8,0.5,1400,2400,1409
...,...,...,...,...,...,...
71,7563,7.0,0.5,1489,7890,1409
72,7753,8.0,0.5,1578,7567,1343
73,10045,6.6,0.5,1489,5672,1278
74,11818,6.7,0.5,1400,2100,1409
75,9410,6.6,0.5,1178,1980,1105
76,11249,6.7,0.5,1578,1890,1343
77,10547,6.8,0.5,1489,1760,1278
78,9851,7.0,0.5,1178,9000,1409
79,10931,8.0,0.5,1578,7890,1343
80,6948,6.6,0.5,1489,2400,1278
81,7883,6.7,0.5,1400,1980,1409
82,6980,6.8,0.5,1178,1890,1343
83,9100,8.0,0.5,1578,1760,1278
84,8342,6.6,0.5,1178,9000,1409
85,7292,6.7,0.5,1578,7890,1105
86,11542,6.8,0.5,1489,7567,1343
87,9049,7.0,0.5,1400,5672,1278
88,8015,8.0,0.5,1178,2100,1409
89,8804,6.6,0.5,1578,1980,1409
90,8452,8.0,0.5,1489,1890,1105
91,10747,6.6,0.5,1178,1760,1343
92,10307,6.7,0.5,1578,9000,1278
93,14108,6.8,0.5,1489,7890,1409
94,8694,7.0,0.5,1400,7567,1343
95,10731,6.6,0.5,1689,1980,1278
96,10916,6.7,0.5,1178,1890,1409
97,9049,6.6,0.5,1578,1760,1278
98,8015,6.7,0.5,1489,9000,1409
99,8804,6.8,0.5,1400,7890,1105
100,8452,7.0,0.5,1178,7567,1343

In [160]:
#################AdaBoost Classifier Algorithm##################

In [161]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [162]:
from sklearn.model_selection import train_test_split

In [163]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [164]:
from sklearn.linear_model import SGDClassifier

In [165]:
a=SGDClassifier()

In [166]:
a=a.fit(X_train,y_train)

In [167]:
print(a.score(X_test,y_test)*10)

2.3943661971830985

In [168]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur',
       'Gram', 'Groundnuts', 'Sessasum', 'Banana', 'Sugarcane', 'Tobacco',
       'Chillies', 'Ginger', 'Tumeric', 'Bajra', 'Maize', 'Cotton', 'Potato',
       'Wheat', 'Other Pulses', 'Barley', 'Jute', 'Mesta'],
      dtype='object')

In [169]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur'])
Crop6=pd.DataFrame(f['Groundnuts'])
Crop7=pd.DataFrame(f['Sessasum'])
Crop8=pd.DataFrame(f['Banana'])
Crop9=pd.DataFrame(f['Sugarcane'])
Crop10=pd.DataFrame(f['Tobacco'])
Crop11=pd.DataFrame(f['Chillies'])
Crop12=pd.DataFrame(f['Ginger'])
Crop13=pd.DataFrame(f['Tumeric'])
Crop14=pd.DataFrame(f['Bajra'])
Crop15=pd.DataFrame(f['Maize'])
Crop16=pd.DataFrame(f['Cotton'])
Crop17=pd.DataFrame(f['Potato'])
Crop18=pd.DataFrame(f['Wheat'])
Crop19=pd.DataFrame(f['Other Pulses'])
Crop20=pd.DataFrame(f['Barley'])
Crop21=pd.DataFrame(f['Jute'])
Crop22=pd.DataFrame(f['Mesta'])

In [170]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)
Parameteronet=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop21],axis=1)
Parameteroneu=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop22],axis=1)

In [171]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur',axis=1)
y4=Parameteroned['Tur']

X5=Parameteronee.drop('Groundnuts',axis=1)
y5=Parameteronee['Groundnuts']

X6=Parameteronef.drop('Sessasum',axis=1)
y6=Parameteronef['Sessasum']

X7=Parameteroneg.drop('Banana',axis=1)
y7=Parameteroneg['Banana']

X8=Parameteroneh.drop('Sugarcane',axis=1)
y8=Parameteroneh['Sugarcane']

X9=Parameteronei.drop('Tobacco',axis=1)
y9=Parameteronei['Tobacco']

X10=Parameteronej.drop('Chillies',axis=1)
y10=Parameteronej['Chillies']

X11=Parameteronek.drop('Ginger',axis=1)
y11=Parameteronek['Ginger']

X12=Parameteronel.drop('Tumeric',axis=1)
y12=Parameteronel['Tumeric']

X13=Parameteronem.drop('Bajra',axis=1)
y13=Parameteronem['Bajra']

X14=Parameteronen.drop('Maize',axis=1)
y14=Parameteronen['Maize']

X15=Parameteroneo.drop('Cotton',axis=1)
y15=Parameteroneo['Cotton']

X16=Parameteronep.drop('Potato',axis=1)
y16=Parameteronep['Potato']

X17=Parameteroneq.drop('Wheat',axis=1)
y17=Parameteroneq['Wheat']

X18=Parameteroner.drop('Other Pulses',axis=1)
y18=Parameteroner['Other Pulses']

X19=Parameterones.drop('Barley',axis=1)
y19=Parameterones['Barley']

X20=Parameteronet.drop('Jute',axis=1)
y20=Parameteronet['Jute']

X21=Parameteroneu.drop('Mesta',axis=1)
y21=Parameteroneu['Mesta']

In [172]:
from sklearn.model_selection import train_test_split

In [173]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train20, X_test20, y_train20, y_test20 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train21, X_test21, y_train21, y_test21 = train_test_split(X18, y18, test_size=0.70,random_state=70)

In [174]:
from sklearn.linear_model import SGDClassifier

In [175]:
b=SGDClassifier()
c=SGDClassifier()
d=SGDClassifier()
e=SGDClassifier()
f=SGDClassifier()
g=SGDClassifier()
h=SGDClassifier()
i=SGDClassifier()
j=SGDClassifier()
k=SGDClassifier()
l=SGDClassifier()
m=SGDClassifier()
n=SGDClassifier()
o=SGDClassifier()
p=SGDClassifier()
q=SGDClassifier()
r=SGDClassifier()
s=SGDClassifier()
t=SGDClassifier()
u=SGDClassifier()
v=SGDClassifier()

In [176]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)
t.fit(X_train19,y_train19)
u.fit(X_train20,y_train20)
v.fit(X_train21,y_train21)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [177]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)
print(t.score(X_test19,y_test19)*10)
print(u.score(X_test20,y_test20)*10)
print(v.score(X_test21,y_test21)*10)

2.3943661971830985
2.3943661971830985
2.3943661971830985
2.3943661971830985
2.3943661971830985
0.23943661971830985
2.3943661971830985
0.23943661971830985
2.3943661971830985
2.3943661971830985
1.0
0.23943661971830985
0.23943661971830985
2.3943661971830985
2.3943661971830985
0.23943661971830985
10.0
2.3943661971830985
2.3943661971830985
2.3943661971830985
2.3943661971830985