In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('OR climate.csv')
b=pd.read_csv('OR Soil.csv')
c=pd.read_csv('OR_groundwater.csv')
d=pd.read_csv('OR_Fertilizers.csv')
e=pd.read_csv('OR Pesticides.csv')
f=pd.read_csv('OR Crop data.csv')

In [3]:
climate=pd.DataFrame(a['Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,14512,6.1,0.01,785,267,1425
1,14092,6.2,1.01,786,268,1426
2,16239,6.3,2.01,787,269,1427
3,17556,6.4,3.01,788,270,1428
4,13873,6.5,4.01,789,271,1429
5,12931,6.2,5.01,790,272,1430
6,13282,6.3,6.01,791,273,1431
7,17556,6.4,7.01,792,274,1432
8,13996,6.3,8.01,793,275,1433
9,17726,6.4,9.01,794,276,1434
10,16558,6.5,10.01,795,277,1435
11,15419,6.2,11.01,796,278,1436
12,16439,6.3,12.01,797,279,1437
13,14536,6.2,13.01,798,280,1438
14,19802,6.3,14.01,799,281,1439
15,11337,6.4,15.01,800,282,1440
16,11476,6.5,16.01,801,283,1441
17,16473,6.2,17.01,802,284,1442
18,15985,6.3,18.01,803,285,1443
19,13773,6.4,19.01,804,286,1444
20,17415,6.3,20.01,805,287,1445
21,15068,6.4,21.01,806,288,1446
22,18599,6.5,22.01,807,289,1447
23,17369,6.2,23.01,808,290,1448
24,15833,6.3,24.01,809,291,1449
25,15035,6.4,25.01,810,292,1450
26,14431,6.5,26.01,811,293,1451
27,17812,6.2,27.01,812,294,1452
28,13900,6.3,28.01,813,295,1453
29,17541,6.4,29.01,814,296,1454
...,...,...,...,...,...,...
71,18824,6.4,71.01,856,338,1496
72,18578,6.5,72.01,857,339,1497
73,13996,6.2,73.01,858,340,1498
74,18857,6.3,74.01,859,341,1499
75,15234,6.2,75.01,860,342,1500
76,17919,6.3,76.01,861,343,1501
77,15271,6.2,77.01,862,344,1502
78,16412,6.3,78.01,863,345,1503
79,16067,6.4,79.01,864,346,1504
80,19132,6.5,80.01,865,347,1505
81,15307,6.2,81.01,866,348,1506
82,16427,6.3,82.01,867,349,1507
83,16339,6.4,83.01,868,350,1508
84,15781,6.3,84.01,869,351,1509
85,14898,6.4,85.01,870,352,1510
86,16782,6.5,86.01,871,353,1511
87,15911,6.2,87.01,872,354,1512
88,20351,6.3,88.01,873,355,1513
89,16612,6.4,89.01,874,356,1514
90,13750,6.5,90.01,875,357,1614
91,10632,6.2,91.01,876,358,1718
92,16438,6.3,92.01,877,359,1719
93,12295,6.4,93.01,878,360,1720
94,18125,6.3,94.01,879,361,1721
95,12511,6.4,95.01,880,362,1722
96,15038,6.5,96.01,881,363,1723
97,14341,6.2,97.01,882,364,1724
98,19132,6.3,98.01,883,365,1725
99,15307,6.2,99.01,884,366,1726
100,16427,6.3,100.01,885,367,1727

In [11]:
#################AdaBoost Classifier Algorithm##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [15]:
from sklearn import svm

In [16]:
a=svm.SVC()

In [17]:
a=a.fit(X_train,y_train)

In [18]:
print(a.score(X_test,y_test)*10)

0.0

In [19]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur'])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Tobacco'])
Crop12=pd.DataFrame(f['Chillies'])
Crop13=pd.DataFrame(f['Ginger'])
Crop14=pd.DataFrame(f['Tumeric'])
Crop15=pd.DataFrame(f['Bajra'])
Crop16=pd.DataFrame(f['Maize'])
Crop17=pd.DataFrame(f['Potato'])
Crop18=pd.DataFrame(f['Wheat'])
Crop19=pd.DataFrame(f['Other Pulses'])
Crop20=pd.DataFrame(f['Jute'])
Crop21=pd.DataFrame(f['Mesta'])
Crop22=pd.DataFrame(f['Cotton'])
Crop23=pd.DataFrame(f['Coconut'])

In [20]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)
Parameteronet=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop21],axis=1)
Parameteroneu=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop22],axis=1)
Parameteronev=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop23],axis=1)

In [21]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur',
       'Gram', 'Groundnuts', 'Sessasum', 'Banana', 'Sugarcane', 'Tobacco',
       'Chillies', 'Ginger', 'Tumeric', 'Bajra', 'Maize', 'Potato', 'Wheat',
       'Other Pulses', 'Jute', 'Mesta', 'Cotton', 'Coconut'],
      dtype='object')

In [22]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur',axis=1)
y4=Parameteroned['Tur']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Tobacco',axis=1)
y10=Parameteronej['Tobacco']

X11=Parameteronek.drop('Chillies',axis=1)
y11=Parameteronek['Chillies']

X12=Parameteronel.drop('Ginger',axis=1)
y12=Parameteronel['Ginger']

X13=Parameteronem.drop('Tumeric',axis=1)
y13=Parameteronem['Tumeric']

X14=Parameteronen.drop('Bajra',axis=1)
y14=Parameteronen['Bajra']

X15=Parameteroneo.drop('Maize',axis=1)
y15=Parameteroneo['Maize']

X16=Parameteronep.drop('Potato',axis=1)
y16=Parameteronep['Potato']

X17=Parameteroneq.drop('Wheat',axis=1)
y17=Parameteroneq['Wheat']

X18=Parameteroner.drop('Other Pulses',axis=1)
y18=Parameteroner['Other Pulses']

X19=Parameterones.drop('Jute',axis=1)
y19=Parameterones['Jute']

X20=Parameteronet.drop('Mesta',axis=1)
y20=Parameteronet['Mesta']

X21=Parameteroneu.drop('Cotton',axis=1)
y21=Parameteroneu['Cotton']

X22=Parameteronev.drop('Coconut',axis=1)
y22=Parameteronev['Coconut']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)
X_train20, X_test20, y_train20, y_test20 = train_test_split(X20, y20, test_size=0.70,random_state=70)
X_train21, X_test21, y_train21, y_test21 = train_test_split(X21, y21, test_size=0.70,random_state=70)
X_train22, X_test22, y_train22, y_test22 = train_test_split(X22, y22, test_size=0.70,random_state=70)

In [25]:
from sklearn import svm

In [26]:
b=svm.SVC()
c=svm.SVC()
d=svm.SVC()
e=svm.SVC()
f=svm.SVC()
g=svm.SVC()
h=svm.SVC()
i=svm.SVC()
j=svm.SVC()
k=svm.SVC()
l=svm.SVC()
m=svm.SVC()
n=svm.SVC()
o=svm.SVC()
p=svm.SVC()
q=svm.SVC()
r=svm.SVC()
s=svm.SVC()
t=svm.SVC()
u=svm.SVC()
v=svm.SVC()

In [27]:
a.fit(X_train1,y_train1)
b.fit(X_train2,y_train2)
c.fit(X_train3,y_train3)
d.fit(X_train4,y_train4)
e.fit(X_train5,y_train5)
f.fit(X_train6,y_train6)
g.fit(X_train7,y_train7)
h.fit(X_train8,y_train8)
i.fit(X_train9,y_train9)
j.fit(X_train10,y_train10)
k.fit(X_train11,y_train11)
l.fit(X_train12,y_train12)
m.fit(X_train13,y_train13)
n.fit(X_train14,y_train14)
o.fit(X_train15,y_train15)
p.fit(X_train16,y_train16)
q.fit(X_train17,y_train17)
r.fit(X_train18,y_train18)
s.fit(X_train19,y_train19)
t.fit(X_train20,y_train20)
u.fit(X_train21,y_train21)
v.fit(X_train22,y_train22)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [28]:
print(a.score(X_test1,y_test1)*10)
print(b.score(X_test2,y_test2)*10)
print(c.score(X_test3,y_test3)*10)
print(d.score(X_test4,y_test4)*10)
print(e.score(X_test5,y_test5)*10)
print(f.score(X_test6,y_test6))
print(g.score(X_test7,y_test7)*10)
print(h.score(X_test8,y_test8))
print(i.score(X_test9,y_test9)*10)
print(j.score(X_test10,y_test10)*10)
print(k.score(X_test11,y_test11))
print(l.score(X_test12,y_test12))
print(m.score(X_test13,y_test13))
print(n.score(X_test14,y_test14)*10)
print(o.score(X_test15,y_test15)*10)
print(p.score(X_test16,y_test16))
print(q.score(X_test17,y_test17)*10)
print(r.score(X_test18,y_test18)*10)
print(s.score(X_test19,y_test19)*10)
print(t.score(X_test20,y_test20)*10)
print(u.score(X_test21,y_test21)*10)
print(v.score(X_test22,y_test22)*10)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.8732394366197183
0.8732394366197183
0.8732394366197183
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
8.873239436619718