In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('WB_climate.csv')
b=pd.read_csv('WB_Soil.csv')
c=pd.read_csv('WB_groundwater.csv')
d=pd.read_csv('WB_Fertilizers.csv')
e=pd.read_csv('WB_Pesticides.csv')
f=pd.read_csv('WB_Crop_data.csv')

In [3]:
climate=pd.DataFrame(a['Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,14512,6.1,0.16,2517,1456,2458
1,14092,6.2,1.16,2518,1457,2459
2,16239,6.3,2.16,2519,1458,2460
3,17556,6.6,3.16,2520,1459,2461
4,13873,6.7,4.16,2521,1460,2462
5,12931,6.2,5.16,2522,1461,2463
6,13282,6.3,6.16,2523,1462,2464
7,17556,6.6,7.16,2524,1463,2465
8,13996,6.7,8.16,2525,1464,2466
9,17726,6.1,9.16,2526,1465,2467
10,16558,6.2,10.16,2527,1466,2468
11,15419,6.3,11.16,2528,1467,2469
12,16439,6.6,12.16,2529,1468,2470
13,14536,6.7,13.16,2530,1469,2471
14,19802,6.2,14.16,2531,1470,2472
15,11337,6.3,15.16,2532,1471,2473
16,11476,6.6,16.16,2533,1472,2474
17,16473,6.3,17.16,2534,1473,2475
18,15985,6.6,18.16,2535,1474,2476
19,13773,6.7,19.16,2536,1475,2477
20,17415,6.2,20.16,2537,1476,2478
21,15068,6.3,21.16,2538,1477,2479
22,18599,6.6,22.16,2539,1478,2480
23,17369,6.7,23.16,2540,1479,2481
24,15833,6.1,24.16,2541,1480,2482
25,15035,6.2,25.16,2542,1481,2483
26,14431,6.3,26.16,2543,1482,2484
27,17812,6.6,27.16,2544,1483,2485
28,13900,6.7,28.16,2545,1484,2486
29,17541,6.2,29.16,2546,1485,2487
...,...,...,...,...,...,...
71,18824,6.6,71.16,2588,1527,2529
72,18578,6.3,72.16,2589,1528,2530
73,13996,6.6,73.16,2590,1529,2531
74,18857,6.7,74.16,2591,1530,2532
75,15234,6.2,75.16,2592,1531,2533
76,17919,6.3,76.16,2593,1532,2534
77,15271,6.6,77.16,2594,1533,2535
78,16412,6.7,78.16,2595,1534,2536
79,16067,6.1,79.16,2596,1535,2537
80,19132,6.2,80.16,2597,1536,2538
81,15307,6.3,81.16,2598,1537,2539
82,16427,6.6,82.16,2599,1538,2540
83,16339,6.7,83.16,2600,1539,2541
84,15781,6.2,84.16,2601,1540,2542
85,14898,6.3,85.16,2602,1541,2543
86,16782,6.2,86.16,2603,1542,2544
87,15911,6.3,87.16,2604,1543,2545
88,20351,6.6,88.16,2605,1544,2546
89,16612,6.7,89.16,2606,1545,2547
90,13750,6.2,90.16,2607,1546,2548
91,10632,6.3,91.16,2608,1547,2549
92,16438,6.6,92.16,2609,1548,2550
93,12295,6.7,93.16,2610,1549,2551
94,18125,6.1,94.16,2611,1550,2552
95,12511,6.2,95.16,2612,1551,2553
96,15038,6.3,96.16,2613,1552,2554
97,14341,6.6,97.16,2614,1553,2555
98,10632,6.7,98.16,2615,1554,2556
99,16438,6.2,99.16,2616,1555,2557
100,12295,6.3,100.16,2617,1556,2558

In [11]:
#################AdaBoost Classifier Algorithm##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [15]:
from sklearn.naive_bayes import BernoulliNB

In [16]:
a=BernoulliNB()

In [17]:
a=a.fit(X_train,y_train)

In [18]:
print(a.score(X_test,y_test)*10)

0.0

In [19]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur',
       'Gram', 'Groundnuts', 'Sessasum', 'Banana', 'Sugarcane', 'Tobacco',
       'Bajra', 'Maize', 'Potato', 'Wheat', 'Other Pulses', 'Barley', 'Jute',
       'Mesta', 'Coconut', 'Tea'],
      dtype='object')

In [22]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur'])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Tobacco'])
Crop12=pd.DataFrame(f['Bajra'])
Crop13=pd.DataFrame(f['Maize'])
Crop14=pd.DataFrame(f['Potato'])
Crop15=pd.DataFrame(f['Wheat'])
Crop16=pd.DataFrame(f['Other Pulses'])
Crop17=pd.DataFrame(f['Barley'])
Crop18=pd.DataFrame(f['Jute'])
Crop19=pd.DataFrame(f['Mesta'])
Crop20=pd.DataFrame(f['Coconut'])
Crop21=pd.DataFrame(f['Tea'])

In [24]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)
Parameteronet=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop21],axis=1)

In [25]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur',axis=1)
y4=Parameteroned['Tur']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Tobacco',axis=1)
y10=Parameteronej['Tobacco']

X11=Parameteronek.drop('Bajra',axis=1)
y11=Parameteronek['Bajra']

X12=Parameteronel.drop('Maize',axis=1)
y12=Parameteronel['Maize']

X13=Parameteronem.drop('Potato',axis=1)
y13=Parameteronem['Potato']

X14=Parameteronen.drop('Wheat',axis=1)
y14=Parameteronen['Wheat']

X15=Parameteroneo.drop('Other Pulses',axis=1)
y15=Parameteroneo['Other Pulses']

X16=Parameteronep.drop('Barley',axis=1)
y16=Parameteronep['Barley']

X17=Parameteroneq.drop('Jute',axis=1)
y17=Parameteroneq['Jute']

X18=Parameteroner.drop('Mesta',axis=1)
y18=Parameteroner['Mesta']

X19=Parameterones.drop('Coconut',axis=1)
y19=Parameterones['Coconut']

X20=Parameteronet.drop('Tea',axis=1)
y20=Parameteronet['Tea']

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)
X_train20, X_test20, y_train20, y_test20 = train_test_split(X20, y20, test_size=0.70,random_state=70)

In [28]:
from sklearn.naive_bayes import BernoulliNB

In [29]:
b=BernoulliNB()
c=BernoulliNB()
d=BernoulliNB()
e=BernoulliNB()
f=BernoulliNB()
g=BernoulliNB()
h=BernoulliNB()
i=BernoulliNB()
j=BernoulliNB()
k=BernoulliNB()
l=BernoulliNB()
m=BernoulliNB()
n=BernoulliNB()
o=BernoulliNB()
p=BernoulliNB()
q=BernoulliNB()
r=BernoulliNB()
s=BernoulliNB()
t=BernoulliNB()
u=BernoulliNB()

In [30]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)
t.fit(X_train19,y_train19)
u.fit(X_train20,y_train20)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [31]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)
print(t.score(X_test19,y_test19)*10)
print(u.score(X_test20,y_test20)*10)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
8.873239436619718