In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('GA-climate.csv')
b=pd.read_csv('GA_Soil.csv')
c=pd.read_csv('GA_groundwater.csv')
d=pd.read_csv('GA_Fertilizers.csv')
e=pd.read_csv('GA-Pesticides.csv')
f=pd.read_csv('GA-Crop-data.csv')

In [3]:
climate=pd.DataFrame(a['Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,6840,8.5,0.1,2421,1414,1902
1,11765,6.5,0.1,2300,1520,2109
2,8542,6.6,0.1,2365,1680,1090
3,4610,6.7,0.1,2400,2000,2013
4,8227,6.8,0.1,2401,1900,2100
5,5813,6.9,0.1,2300,1902,2220
6,12961,7.0,0.1,2365,1950,2103
7,13625,7.1,0.1,2400,1680,2220
8,8122,7.2,0.1,2401,2000,1902
9,7700,7.3,0.1,2300,1900,2109
10,8784,7.4,0.1,2365,1902,1890
11,10310,7.8,0.1,2400,1950,2013
12,8886,8.0,0.1,2401,2100,2100
13,11948,8.1,0.1,2300,1900,1890
14,10023,8.2,0.1,2365,1902,2013
15,7580,8.3,0.1,2400,1950,2100
16,6200,8.5,0.1,2401,1680,2220
17,11998,6.5,0.1,2300,2000,2103
18,7869,6.6,0.1,2365,1900,2220
19,6094,6.7,0.1,2400,1902,1902
20,8021,6.8,0.1,2401,1950,2109
21,10247,6.9,0.1,2300,2100,1890
22,10972,7.0,0.1,2365,2000,2013
23,8908,7.1,0.1,2400,1900,2100
24,13372,7.2,0.1,2401,1902,2109
25,12754,7.3,0.1,2300,1950,1090
26,11337,7.4,0.1,2365,1680,2013
27,8970,7.8,0.1,2401,2000,2100
28,4518,8.0,0.1,2300,1900,2220
29,7991,8.1,0.1,2365,1902,2103
...,...,...,...,...,...,...
71,6275,8.2,0.1,2300,1680,2220
72,8205,8.3,0.1,2365,2000,1902
73,8718,8.5,0.1,2401,1520,2109
74,13598,6.5,0.1,2300,1680,1890
75,6696,6.6,0.1,2400,2000,2013
76,8168,6.7,0.1,2401,1900,2100
77,11398,6.8,0.1,2300,1902,2109
78,10267,6.9,0.1,2365,1950,1090
79,6388,7.0,0.1,2400,1680,2013
80,6005,7.1,0.1,2401,2000,2100
81,8543,7.2,0.1,2300,1900,2220
82,6705,7.3,0.1,2365,1902,2103
83,11374,7.4,0.1,2400,1950,2220
84,9650,7.8,0.1,2401,2100,1902
85,10237,8.0,0.1,2300,1900,2109
86,12452,8.1,0.1,2365,1902,1890
87,12050,8.2,0.1,2400,1950,2013
88,9504,6.6,0.1,2401,1680,2100
89,6319,6.7,0.1,2300,2000,1890
90,12471,6.8,0.1,2365,1900,2013
91,9648,6.9,0.1,2400,1902,2100
92,7582,7.0,0.1,2401,1950,2220
93,14303,7.1,0.1,2300,2100,2103
94,9192,7.2,0.1,2365,2000,2220
95,6748,7.3,0.1,2400,1900,1902
96,7087,7.4,0.1,2401,1902,2109
97,7582,7.8,0.1,2300,1950,2103
98,14303,8.0,0.1,2365,1680,2220
99,9192,8.1,0.1,2401,2000,1902
100,12050,8.2,0.1,2300,1900,2109

In [11]:
#################AdaBoost Classifier Algorithm##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
a=RandomForestClassifier()

In [17]:
a=a.fit(X_train,y_train)

In [18]:
print(a.score(X_test,y_test)*10)

2.112676056338028

In [19]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur',
       'Gram', 'Groundnuts', 'Sessasum', 'Banana', 'Sugarcane', 'Tobacco',
       'Coconut', 'Bajra', 'Maize', 'Cotton', 'Potato', 'Wheat',
       'Other Pulses'],
      dtype='object')

In [52]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur'])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Tobacco'])
Crop12=pd.DataFrame(f['Coconut'])
Crop13=pd.DataFrame(f['Bajra'])
Crop14=pd.DataFrame(f['Maize'])
Crop15=pd.DataFrame(f['Cotton'])
Crop16=pd.DataFrame(f['Potato'])
Crop17=pd.DataFrame(f['Wheat'])
Crop18=pd.DataFrame(f['Other Pulses'])

In [53]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)

In [54]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur',axis=1)
y4=Parameteroned['Tur']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Tobacco',axis=1)
y10=Parameteronej['Tobacco']

X11=Parameteronek.drop('Coconut',axis=1)
y11=Parameteronek['Coconut']

X12=Parameteronel.drop('Bajra',axis=1)
y12=Parameteronel['Bajra']

X13=Parameteronem.drop('Maize',axis=1)
y13=Parameteronem['Maize']

X14=Parameteronen.drop('Cotton',axis=1)
y14=Parameteronen['Cotton']

X15=Parameteroneo.drop('Potato',axis=1)
y15=Parameteroneo['Potato']

X16=Parameteronep.drop('Wheat',axis=1)
y16=Parameteronep['Wheat']

X17=Parameteroneq.drop('Other Pulses',axis=1)
y17=Parameteroneq['Other Pulses']

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)

In [57]:
from sklearn.ensemble import RandomForestClassifier

In [58]:
b=RandomForestClassifier()
c=RandomForestClassifier()
d=RandomForestClassifier()
e=RandomForestClassifier()
f=RandomForestClassifier()
g=RandomForestClassifier()
h=RandomForestClassifier()
i=RandomForestClassifier()
j=RandomForestClassifier()
k=RandomForestClassifier()
l=RandomForestClassifier()
m=RandomForestClassifier()
n=RandomForestClassifier()
o=RandomForestClassifier()
p=RandomForestClassifier()
q=RandomForestClassifier()
r=RandomForestClassifier()

In [59]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [60]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)

2.535211267605634
3.52112676056338
3.23943661971831
2.535211267605634
2.535211267605634
0.2535211267605634
2.535211267605634
0.2535211267605634
2.535211267605634
2.535211267605634
0.2535211267605634
0.2535211267605634
0.2535211267605634
10.0
2.535211267605634
0.2535211267605634
2.535211267605634