In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('AP climate.csv')
b=pd.read_csv('AP_Soil.csv')
c=pd.read_csv('AP_groundwater.csv')
d=pd.read_csv('AP_Fertilizers.csv')
e=pd.read_csv('AP Pesticides.csv')
f=pd.read_csv('AP Crop data.csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,7934,6.5,0.02,3120,53,3242
1,9250,8.2,0.02,4062,47,3034
2,8943,8.0,0.07,3241,67,512
3,9471,7.0,0.02,2567,64,3148
4,9769,8.2,0.02,2100,48,3062
5,12049,8.2,0.02,1878,43,3034
6,7599,8.0,0.07,3241,48,3148
7,10400,7.0,0.02,2567,67,2921
8,9549,8.2,0.03,2500,64,3242
9,8618,8.0,0.05,2501,48,3034
10,12727,7.0,0.02,2409,43,512
11,11317,8.2,0.02,3241,48,3148
12,9130,8.2,0.07,2567,47,3062
13,9543,8.0,0.02,2100,67,3034
14,7876,7.0,0.02,1878,64,3148
15,6368,8.0,0.02,3241,48,2921
16,6000,7.0,0.02,2567,43,3034
17,12007,8.2,0.07,2500,48,3148
18,8128,8.2,0.02,2501,67,2921
19,10738,8.0,0.03,2409,64,3242
20,10801,7.0,0.05,1878,48,3034
21,11659,8.2,0.02,3241,53,512
22,9533,8.0,0.02,2567,47,3148
23,7321,7.0,0.07,2500,67,3062
24,10066,8.2,0.07,2501,64,3034
25,12331,8.2,0.02,2409,48,3148
26,8189,8.0,0.02,3241,43,2921
27,10777,7.0,0.02,2567,48,3172
28,9534,8.2,0.07,2100,67,3242
29,8951,8.0,0.02,1878,64,3034
...,...,...,...,...,...,...
71,9181,8.0,0.02,2567,43,3034
72,15015,7.0,0.03,2100,48,3148
73,12303,8.2,0.05,1878,67,2921
74,10710,8.0,0.02,3241,64,3172
75,9470,7.0,0.02,2567,48,2921
76,10900,8.2,0.07,2566,43,3172
77,13576,7.0,0.02,2543,48,3242
78,12765,8.2,0.03,3241,47,3034
79,11700,8.0,0.05,2567,67,512
80,11966,7.0,0.02,2500,64,3148
81,7395,8.2,0.02,2501,48,3062
82,7000,8.2,0.07,2409,43,3034
83,10590,8.0,0.07,3241,48,3148
84,9989,7.0,0.02,1878,64,2921
85,7306,8.2,0.02,3241,48,3242
86,9932,8.0,0.02,2567,43,3034
87,9190,7.0,0.07,2500,48,512
88,11860,8.2,0.02,2501,67,3148
89,11470,8.0,0.03,2409,64,3062
90,10750,7.0,0.05,1878,48,3034
91,10593,8.2,0.02,3241,43,3148
92,7915,8.2,0.02,2567,48,2921
93,17047,8.0,0.07,2500,47,3172
94,7926,7.0,0.02,2500,67,3062
95,11917,8.0,0.02,2501,64,3034
96,10461,7.0,0.02,2409,48,3148
97,7215,8.2,0.04,3241,43,3148
98,9460,8.2,0.02,2567,48,2921
99,8028,8.0,0.07,2100,41,3172
100,9005,7.0,0.02,1878,48,3062

In [11]:
#################AdaBoost Classifier Algorithm##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
a=DecisionTreeClassifier()

In [17]:
a=a.fit(X_train,y_train)

In [18]:
print(a.score(X_test,y_test))

0.1267605633802817

In [19]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur ',
       'Gram', 'Groundnuts', 'Sessasum', 'Banana', 'Sugarcane', 'Tobacco',
       'Chillies', 'Ginger', 'Coconut', 'Tumeric', 'Bajra', 'Maize', 'Cotton',
       'Potato', 'Wheat', 'Other Pulses', 'Mesta'],
      dtype='object')

In [20]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur '])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Tobacco'])
Crop12=pd.DataFrame(f['Chillies'])
Crop13=pd.DataFrame(f['Ginger'])
Crop14=pd.DataFrame(f['Coconut'])
Crop15=pd.DataFrame(f['Tumeric'])
Crop16=pd.DataFrame(f['Bajra'])
Crop17=pd.DataFrame(f['Maize'])
Crop18=pd.DataFrame(f['Cotton'])
Crop19=pd.DataFrame(f['Potato'])
Crop20=pd.DataFrame(f['Wheat'])
Crop21=pd.DataFrame(f['Other Pulses'])
Crop22=pd.DataFrame(f['Mesta'])

In [21]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)
Parameteronet=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop21],axis=1)
Parameteroneu=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop22],axis=1)

In [22]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur ',axis=1)
y4=Parameteroned['Tur ']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Tobacco',axis=1)
y10=Parameteronej['Tobacco']

X11=Parameteronek.drop('Chillies',axis=1)
y11=Parameteronek['Chillies']

X12=Parameteronel.drop('Ginger',axis=1)
y12=Parameteronel['Ginger']

X13=Parameteronem.drop('Coconut',axis=1)
y13=Parameteronem['Coconut']

X14=Parameteronen.drop('Tumeric',axis=1)
y14=Parameteronen['Tumeric']

X15=Parameteroneo.drop('Bajra',axis=1)
y15=Parameteroneo['Bajra']

X16=Parameteronep.drop('Maize',axis=1)
y16=Parameteronep['Maize']

X17=Parameteroneq.drop('Cotton',axis=1)
y17=Parameteroneq['Cotton']

X18=Parameteroner.drop('Potato',axis=1)
y18=Parameteroner['Potato']

X19=Parameterones.drop('Wheat',axis=1)
y19=Parameterones['Wheat']

X20=Parameteronet.drop('Other Pulses',axis=1)
y20=Parameteronet['Other Pulses']

X21=Parameteroneu.drop('Mesta',axis=1)
y21=Parameteroneu['Mesta']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)
X_train20, X_test20, y_train20, y_test20 = train_test_split(X20, y20, test_size=0.70,random_state=70)
X_train21, X_test21, y_train21, y_test21 = train_test_split(X21, y21, test_size=0.70,random_state=70)

In [25]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
b=DecisionTreeClassifier()
c=DecisionTreeClassifier()
d=DecisionTreeClassifier()
e=DecisionTreeClassifier()
f=DecisionTreeClassifier()
g=DecisionTreeClassifier()
h=DecisionTreeClassifier()
i=DecisionTreeClassifier()
j=DecisionTreeClassifier()
k=DecisionTreeClassifier()
l=DecisionTreeClassifier()
m=DecisionTreeClassifier()
n=DecisionTreeClassifier()
o=DecisionTreeClassifier()
p=DecisionTreeClassifier()
q=DecisionTreeClassifier()
r=DecisionTreeClassifier()
s=DecisionTreeClassifier()
t=DecisionTreeClassifier()
u=DecisionTreeClassifier()
v=DecisionTreeClassifier()

In [38]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)
t.fit(X_train19,y_train19)
u.fit(X_train20,y_train20)
v.fit(X_train21,y_train21)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [43]:
print(b.score(X_test1,y_test1))
print(c.score(X_test2,y_test2))
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)
print(t.score(X_test19,y_test19)*10)
print(u.score(X_test20,y_test20)*10)
print(v.score(X_test21,y_test21)*10)

0.2535211267605634
0.2535211267605634
0.8450704225352113
0.8450704225352113
0.8450704225352113
0.08450704225352113
0.8450704225352113
0.08450704225352113
0.8450704225352113
0.8450704225352113
0.08450704225352113
0.08450704225352113
0.08450704225352113
0.8450704225352113
0.8450704225352113
0.08450704225352113
0.8450704225352113
0.8450704225352113
0.8450704225352113
0.8450704225352113
0.8450704225352113