In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('climate Test1.csv')
b=pd.read_csv('Soil Test1.csv')
c=pd.read_csv('groundwater Test1.csv')
d=pd.read_csv('Fertilizers Test1.csv')
e=pd.read_csv('Pesticides Test1.csv')
f=pd.read_csv('Crop data Test1.csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,31399,4.4,0.30,122.70,985,3001
1,26064,3.8,0.78,208.30,113,2875
2,23132,6.3,0.45,260.91,239,2297
3,24844,6.2,0.56,264.89,233,2347
4,29248,5.9,0.13,283.54,100,2129
5,31578,5.5,0.23,113.20,200,2556
6,27569,2.5,0.50,106.93,350,2452
7,30785,6.6,0.09,62.49,466,2733
8,27039,4.5,0.20,40.55,250,2576
9,32996,5.2,0.30,123.40,113,2551
10,33282,2.5,0.05,300.40,500,2531
11,39072,6.6,0.13,250.34,236,2512
12,31442,4.5,0.23,235.30,100,2345
13,25012,5.2,0.50,122.70,200,2290
14,25814,6.0,0.09,208.30,350,2660
15,22182,6.1,0.20,260.91,466,2334
16,23877,3.1,0.30,264.89,985,2297
17,26950,4.4,0.78,283.54,113,2347
18,32991,3.8,0.45,113.20,355,2129
19,27165,6.3,0.56,106.93,233,2556
20,27375,6.2,0.13,62.49,113,2452
21,30586,5.9,0.23,235.30,355,2733
22,28319,5.5,0.50,122.70,233,2576
23,24072,2.5,0.34,208.30,100,2551
24,23402,6.6,0.56,260.91,200,2531
25,29458,4.5,0.79,264.89,350,1693
26,35939,5.2,0.71,283.54,117,1588
27,21720,6.0,0.09,113.20,439,2345
28,31537,6.1,0.20,106.93,276,3001
29,31695,3.1,0.30,62.49,275,2875
30,26993,4.4,0.78,235.30,213,2297

In [11]:
#################KNN##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
Parameterone.columns

Index([' Rainfall', 'Ph', 'Rise (Depth of Water)', 'NPK(tonnes)',
       'MALATHION(QTY)(kg)', 'Rice(kg/hectare)'],
      dtype='object')

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
a=KNeighborsClassifier()

In [18]:
a=a.fit(X_train,y_train)

In [19]:
print(a.score(X_test,y_test)*10)

0.9090909090909092

In [20]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur ',
       'Other Pulses', 'Groundnuts', 'Sessasum', 'Tea', 'Banana', 'Sugarcane',
       'Tobacco', 'Pepper', 'Chillies', 'Ginger', 'Coconut', 'Tumeric',
       'Coffee', 'Rubber'],
      dtype='object')

In [21]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur '])
Crop6=pd.DataFrame(f['Other Pulses'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Tea'])
Crop10=pd.DataFrame(f['Banana'])
Crop11=pd.DataFrame(f['Sugarcane'])
Crop12=pd.DataFrame(f['Tobacco'])
Crop13=pd.DataFrame(f['Pepper'])
Crop14=pd.DataFrame(f['Chillies'])
Crop15=pd.DataFrame(f['Ginger'])
Crop16=pd.DataFrame(f['Coconut'])
Crop17=pd.DataFrame(f['Tumeric'])
Crop18=pd.DataFrame(f['Coffee'])
Crop19=pd.DataFrame(f['Rubber'])

In [22]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)

In [23]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur ',axis=1)
y4=Parameteroned['Tur ']

X5=Parameteronee.drop('Other Pulses',axis=1)
y5=Parameteronee['Other Pulses']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Tea',axis=1)
y8=Parameteroneh['Tea']

X9=Parameteronei.drop('Banana',axis=1)
y9=Parameteronei['Banana']

X10=Parameteronej.drop('Sugarcane',axis=1)
y10=Parameteronej['Sugarcane']

X11=Parameteronek.drop('Tobacco',axis=1)
y11=Parameteronek['Tobacco']

X12=Parameteronel.drop('Pepper',axis=1)
y12=Parameteronel['Pepper']

X13=Parameteronem.drop('Chillies',axis=1)
y13=Parameteronem['Chillies']

X14=Parameteronen.drop('Ginger',axis=1)
y14=Parameteronen['Ginger']

X15=Parameteroneo.drop('Coconut',axis=1)
y15=Parameteroneo['Coconut']

X16=Parameteronep.drop('Tumeric',axis=1)
y16=Parameteronep['Tumeric']

X17=Parameteroneq.drop('Coffee',axis=1)
y17=Parameteroneq['Coffee']

X18=Parameteroner.drop('Rubber',axis=1)
y18=Parameteroner['Rubber']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)

In [26]:
from sklearn.neighbors import KNeighborsClassifier

In [27]:
b=KNeighborsClassifier(n_neighbors=3)
c=KNeighborsClassifier(n_neighbors=3)
d=KNeighborsClassifier(n_neighbors=3)
e=KNeighborsClassifier(n_neighbors=3)
f=KNeighborsClassifier(n_neighbors=3)
g=KNeighborsClassifier(n_neighbors=3)
h=KNeighborsClassifier(n_neighbors=3)
i=KNeighborsClassifier(n_neighbors=3)
j=KNeighborsClassifier(n_neighbors=3)
k=KNeighborsClassifier(n_neighbors=3)
l=KNeighborsClassifier(n_neighbors=3)
m=KNeighborsClassifier(n_neighbors=3)
n=KNeighborsClassifier(n_neighbors=3)
o=KNeighborsClassifier(n_neighbors=3)
p=KNeighborsClassifier(n_neighbors=3)
q=KNeighborsClassifier(n_neighbors=3)
r=KNeighborsClassifier(n_neighbors=3)
s=KNeighborsClassifier(n_neighbors=3)

In [28]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [29]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3))
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5))
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15))
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)

0.0
0.0
0.045454545454545456
0.0
0.0
0.0
0.0
0.22727272727272727
0.4545454545454546
0.9090909090909092
0.0
0.045454545454545456
0.13636363636363635
0.4545454545454546
0.0
0.13636363636363635
0.0
0.9090909090909092