In [11]:
import numpy as np
import pandas as pd

In [12]:
a=pd.read_csv('climate Test1.csv')
b=pd.read_csv('Soil Test1.csv')
c=pd.read_csv('groundwater Test1.csv')
d=pd.read_csv('Fertilizers Test1.csv')
e=pd.read_csv('Pesticides Test1.csv')
f=pd.read_csv('Crop data Test1.csv')

In [13]:
climate=pd.DataFrame(a[' Rainfall'])

In [14]:
Soil=pd.DataFrame(b['Ph'])

In [15]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [16]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [17]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [18]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [19]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [20]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,6604,8.1,0.05,2164,7670,1704
1,5770,8.2,0.05,2165,7671,1705
2,5103,9.0,0.05,2166,7672,1706
3,6950,9.3,0.05,2167,7673,1707
4,7501,7.6,0.05,2168,7674,1708
5,8543,7.7,0.05,2169,7675,1709
6,10402,8.1,0.05,2170,7676,1710
7,7389,8.2,0.05,2171,7677,1711
8,8368,8.3,0.05,2172,7678,1712
9,8773,8.4,0.05,2173,7679,1713
10,7204,8.5,0.05,2174,7680,1714
11,8403,7.7,0.05,2175,7681,1715
12,7697,8.0,0.05,2176,7682,1716
13,7516,8.1,0.05,2177,7683,1717
14,8001,8.2,0.05,2178,879,1718
15,6485,9.0,0.05,2179,880,1719
16,6423,9.3,0.05,2180,881,1378
17,8551,7.6,0.05,2181,882,1678
18,6481,7.7,0.05,2182,883,1679
19,8462,8.1,0.05,2183,884,1680
20,7886,8.2,0.05,2184,885,1681
21,6170,8.3,0.05,2185,886,1682
22,4089,7.6,0.05,3200,887,1683
23,8032,7.7,0.05,3201,888,1684
24,7718,8.0,0.05,3202,889,1685
25,9012,8.1,0.05,3203,890,1686
26,7488,8.2,0.05,3204,891,1687
27,6855,9.0,0.05,3205,892,1688
28,6940,9.3,0.05,3206,893,1689
29,8287,7.6,0.05,3207,894,1690
30,6498,7.7,0.05,3208,895,1691

In [23]:
#################AdaBoost Classifier Algorithm##################

X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

from sklearn.neighbors import KNeighborsClassifier

a=KNeighborsClassifier()

a=a.fit(X_train,y_train)

print(a.score(X_test,y_test)*10)

Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur '])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Tobacco'])
Crop12=pd.DataFrame(f['Coconut'])
Crop13=pd.DataFrame(f['Bajra'])
Crop14=pd.DataFrame(f['Maize'])
Crop15=pd.DataFrame(f['Cotton'])
Crop16=pd.DataFrame(f['Potato'])
Crop17=pd.DataFrame(f['Wheat'])
Crop18=pd.DataFrame(f['Other Pulses'])
Crop19=pd.DataFrame(f['Mesta'])
Crop20=pd.DataFrame(f['Barley'])

Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)

X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur ',axis=1)
y4=Parameteroned['Tur ']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Tobacco',axis=1)
y10=Parameteronej['Tobacco']

X11=Parameteronek.drop('Coconut',axis=1)
y11=Parameteronek['Coconut']

X12=Parameteronel.drop('Bajra',axis=1)
y12=Parameteronel['Bajra']

X13=Parameteronem.drop('Maize',axis=1)
y13=Parameteronem['Maize']

X14=Parameteronen.drop('Cotton',axis=1)
y14=Parameteronen['Cotton']

X15=Parameteroneo.drop('Potato',axis=1)
y15=Parameteroneo['Potato']

X16=Parameteronep.drop('Wheat',axis=1)
y16=Parameteronep['Wheat']

X17=Parameteroneq.drop('Other Pulses',axis=1)
y17=Parameteroneq['Other Pulses']

X18=Parameteroner.drop('Mesta',axis=1)
y18=Parameteroner['Mesta']

X19=Parameterones.drop('Barley',axis=1)
y19=Parameterones['Barley']

from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)

from sklearn.neighbors import KNeighborsClassifier


b=KNeighborsClassifier()
c=KNeighborsClassifier()
d=KNeighborsClassifier()
e=KNeighborsClassifier()
f=KNeighborsClassifier()
g=KNeighborsClassifier()
h=KNeighborsClassifier()
i=KNeighborsClassifier()
j=KNeighborsClassifier()
k=KNeighborsClassifier()
l=KNeighborsClassifier()
m=KNeighborsClassifier()
n=KNeighborsClassifier()
o=KNeighborsClassifier()
p=KNeighborsClassifier()
q=KNeighborsClassifier()
r=KNeighborsClassifier()
s=KNeighborsClassifier()
t=KNeighborsClassifier()

b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)
t.fit(X_train19,y_train19)

print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)
print(t.score(X_test19,y_test19)*10)

0.0
10.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0