In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('BH-climate.csv')
b=pd.read_csv('BH-Soil.csv')
c=pd.read_csv('BH_groundwater.csv')
d=pd.read_csv('BH_Fertilizers.csv')
e=pd.read_csv('BH-Pesticides.csv')
f=pd.read_csv('BH_crop_data.csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,11689,7.5,0.21,1780,899,1563
1,14230,8.0,0.21,1781,900,1564
2,13965,8.1,0.21,1782,901,1565
3,9207,8.2,0.21,1783,902,1566
4,14250,8.3,0.21,1784,903,1567
5,11354,8.4,0.21,1785,904,1568
6,10919,7.7,0.21,1786,905,1569
7,9467,8.0,0.21,1787,906,1570
8,12611,8.1,0.21,1788,907,1571
9,14023,8.2,0.21,1789,908,1572
10,10667,8.3,0.21,1790,909,1573
11,11797,8.4,0.21,1791,910,1574
12,8476,8.1,0.21,1792,911,1575
13,13332,8.2,0.21,1793,912,1576
14,11729,8.3,0.21,1794,913,1577
15,11315,8.4,0.21,1795,914,1578
16,15484,7.7,0.21,1796,915,1579
17,13471,8.0,0.21,1797,916,1580
18,15006,8.1,0.21,1798,917,1581
19,11919,8.2,0.21,1799,918,1582
20,11276,8.3,0.21,1800,919,1583
21,11632,8.0,0.21,1801,920,1584
22,12716,8.1,0.21,1802,921,1585
23,10640,8.2,0.21,1803,922,1586
24,10784,8.3,0.21,1804,923,1587
25,11868,8.4,0.21,1805,924,1588
26,14167,7.7,0.21,1806,925,1589
27,10701,8.0,0.21,1807,926,1590
28,13218,8.1,0.21,1808,927,1591
29,16155,8.2,0.21,1809,928,1592
...,...,...,...,...,...,...
71,10866,8.2,0.21,1851,970,1634
72,8682,8.3,0.21,1852,971,1635
73,13205,8.4,0.21,1853,972,1636
74,11205,7.7,0.21,1854,973,1637
75,12293,8.2,0.21,1855,974,1638
76,12819,8.3,0.21,1856,975,1639
77,15221,8.4,0.21,1857,976,1640
78,14038,7.7,0.21,1858,977,1641
79,14477,8.0,0.21,1859,978,1642
80,12935,8.1,0.21,1860,979,1643
81,10662,8.2,0.21,1861,980,1644
82,9498,8.3,0.21,1862,981,1645
83,12659,8.4,0.21,1863,982,1646
84,11588,8.1,0.21,1864,983,1647
85,9957,8.2,0.21,1865,984,1648
86,12030,8.3,0.21,1866,985,1649
87,15206,8.4,0.21,1867,986,1650
88,13118,7.7,0.21,1868,987,1651
89,10051,8.0,0.21,1869,988,1652
90,9389,8.1,0.21,1870,989,1653
91,13384,8.2,0.21,1871,990,1654
92,9495,8.3,0.21,1872,991,1655
93,11484,8.0,0.21,1873,992,1656
94,10409,8.1,0.21,1874,993,1657
95,8911,8.2,0.21,1875,994,1658
96,11687,8.3,0.21,1876,995,1659
97,13384,8.4,0.21,1877,996,1660
98,9495,7.7,0.21,1878,997,1661
99,11484,8.0,0.21,1879,998,1662
100,11354,8.1,0.21,1880,999,1663

In [11]:
#################AdaBoost Classifier Algorithm##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [15]:
from sklearn.ensemble import RandomForestClassifier

In [16]:
a=RandomForestClassifier()

In [17]:
a=a.fit(X_train,y_train)

In [18]:
print(a.score(X_test,y_test)*10)

0.0

In [19]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Ragi', 'Small Millets', 'Tur ', 'Gram',
       'Groundnuts', 'Sessasum', 'Sugarcane', 'Maize', 'Potato', 'Wheat',
       'Other Pulses', 'Barley', 'Jowar', 'Bajra', 'Jute ', 'Mesta', 'Tobacco',
       'Banana ', 'Coconut'],
      dtype='object')

In [21]:
Crop2=pd.DataFrame(f['Ragi'])
Crop3=pd.DataFrame(f['Small Millets'])
Crop4=pd.DataFrame(f['Tur '])
Crop5=pd.DataFrame(f['Gram'])
Crop6=pd.DataFrame(f['Groundnuts'])
Crop7=pd.DataFrame(f['Sessasum'])
Crop8=pd.DataFrame(f['Sugarcane'])
Crop9=pd.DataFrame(f['Maize'])
Crop10=pd.DataFrame(f['Potato'])
Crop11=pd.DataFrame(f['Wheat'])
Crop12=pd.DataFrame(f['Other Pulses'])
Crop13=pd.DataFrame(f['Barley'])
Crop14=pd.DataFrame(f['Jowar'])
Crop15=pd.DataFrame(f['Bajra'])
Crop16=pd.DataFrame(f['Jute '])
Crop17=pd.DataFrame(f['Mesta'])
Crop18=pd.DataFrame(f['Tobacco'])
Crop19=pd.DataFrame(f['Banana '])
Crop20=pd.DataFrame(f['Coconut'])

In [22]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)

In [24]:
X1=Parameteronea.drop('Ragi',axis=1)
y1=Parameteronea['Ragi']

X2=Parameteroneb.drop('Small Millets',axis=1)
y2=Parameteroneb['Small Millets']

X3=Parameteronec.drop('Tur ',axis=1)
y3=Parameteronec['Tur ']

X4=Parameteroned.drop('Gram',axis=1)
y4=Parameteroned['Gram']

X5=Parameteronee.drop('Groundnuts',axis=1)
y5=Parameteronee['Groundnuts']

X6=Parameteronef.drop('Sessasum',axis=1)
y6=Parameteronef['Sessasum']

X7=Parameteroneg.drop('Sugarcane',axis=1)
y7=Parameteroneg['Sugarcane']

X8=Parameteroneh.drop('Maize',axis=1)
y8=Parameteroneh['Maize']

X9=Parameteronei.drop('Potato',axis=1)
y9=Parameteronei['Potato']

X10=Parameteronej.drop('Wheat',axis=1)
y10=Parameteronej['Wheat']

X11=Parameteronek.drop('Other Pulses',axis=1)
y11=Parameteronek['Other Pulses']

X12=Parameteronel.drop('Barley',axis=1)
y12=Parameteronel['Barley']

X13=Parameteronem.drop('Jowar',axis=1)
y13=Parameteronem['Jowar']

X14=Parameteronen.drop('Bajra',axis=1)
y14=Parameteronen['Bajra']

X15=Parameteroneo.drop('Jute ',axis=1)
y15=Parameteroneo['Jute ']

X16=Parameteronep.drop('Mesta',axis=1)
y16=Parameteronep['Mesta']

X17=Parameteroneq.drop('Tobacco',axis=1)
y17=Parameteroneq['Tobacco']

X18=Parameteroner.drop('Banana ',axis=1)
y18=Parameteroner['Banana ']

X19=Parameterones.drop('Coconut',axis=1)
y19=Parameterones['Coconut']

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)
X_train20, X_test20, y_train20, y_test20 = train_test_split(X19, y19, test_size=0.70,random_state=70)

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
b=RandomForestClassifier()
c=RandomForestClassifier()
d=RandomForestClassifier()
e=RandomForestClassifier()
f=RandomForestClassifier()
g=RandomForestClassifier()
h=RandomForestClassifier()
i=RandomForestClassifier()
j=RandomForestClassifier()
k=RandomForestClassifier()
l=RandomForestClassifier()
m=RandomForestClassifier()
n=RandomForestClassifier()
o=RandomForestClassifier()
p=RandomForestClassifier()
q=RandomForestClassifier()
r=RandomForestClassifier()
s=RandomForestClassifier()
t=RandomForestClassifier()
u=RandomForestClassifier()

In [29]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)
t.fit(X_train19,y_train19)
u.fit(X_train20,y_train20)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [31]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8)*10)
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)
print(t.score(X_test19,y_test19)*10)
print(u.score(X_test20,y_test20)*10)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
10.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
10.0
10.0