In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('TN climate.csv')
b=pd.read_csv('TN_Soil.csv')
c=pd.read_csv('TN_groundwater.csv')
d=pd.read_csv('TN_Fertilizers.csv')
e=pd.read_csv('TN Pesticides.csv')
f=pd.read_csv('TN Crop data.csv')

In [3]:
climate=pd.DataFrame(a['Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,11567,6.5,0.43,1556,47,2712
1,10466,7.5,0.57,1597,52,3100
2,10845,6.0,0.01,1639,52,3918
3,9890,6.3,0.56,1680,53,2712
4,10087,7.1,0.57,1639,47,3100
5,9209,7.3,0.01,1680,67,3100
6,10484,7.4,0.56,1514,60,2712
7,7536,6.8,0.56,1556,56,3100
8,7659,6.4,0.78,1514,47,3918
9,8709,6.5,0.57,1639,52,3069
10,9164,6.2,0.01,1680,52,3039
11,12381,6.0,0.56,1514,53,3918
12,10609,7.4,0.78,1556,47,2712
13,10158,7.1,0.57,1597,67,3100
14,8822,7.3,0.01,1639,53,3918
15,8213,7.4,0.56,1680,47,2712
16,7911,6.8,0.78,1639,67,3100
17,8531,6.4,0.01,1680,60,3100
18,9534,6.5,0.56,1514,56,3918
19,7203,6.2,0.78,1556,47,2712
20,10719,6.0,0.57,1639,52,3100
21,11192,7.4,0.57,1680,52,3918
22,9328,7.5,0.01,1514,53,3069
23,8244,6.0,0.56,1556,47,3039
24,11510,6.3,0.56,1597,67,3918
25,11411,7.1,0.78,1639,60,2712
26,10000,7.3,0.57,1680,56,3100
27,6746,7.4,0.01,1680,47,3918
28,12629,6.8,0.56,1514,52,2712
29,8697,6.4,0.78,1556,52,3100
...,...,...,...,...,...,...
71,7845,6.5,0.01,1514,47,3918
72,8434,6.2,0.56,1556,52,3069
73,8739,6.0,0.78,1597,52,3039
74,8648,7.4,0.01,1639,53,2712
75,10977,7.5,0.56,1680,47,3100
76,8477,6.0,0.78,1639,67,3918
77,8318,6.3,0.57,1680,60,3069
78,11101,7.1,0.57,1514,56,3039
79,10622,7.3,0.01,1639,53,3918
80,9887,7.4,0.56,1680,47,2712
81,8193,6.8,0.56,1514,67,3100
82,8000,6.4,0.78,1556,60,3918
83,9794,6.5,0.57,1597,56,2712
84,7347,6.2,0.56,1639,47,3100
85,6947,7.3,0.78,1680,52,3100
86,7089,7.4,0.57,1639,52,2712
87,9941,6.8,0.01,1680,53,3100
88,12731,6.4,0.56,1514,47,3918
89,9514,6.5,0.78,1556,67,3069
90,9491,6.2,0.57,1639,60,3039
91,12792,6.0,0.01,1680,52,3918
92,9637,7.4,0.56,1514,53,2712
93,12012,7.1,0.78,1556,47,3100
94,10675,6.2,0.01,1597,52,3918
95,7801,6.0,0.56,1639,52,2712
96,7899,7.4,0.78,1680,53,3100
97,8677,7.5,0.57,1639,47,3100
98,12164,6.0,0.01,1680,67,3918
99,5272,6.3,0.56,1514,60,3069
100,6780,7.1,0.78,1556,56,3078

In [11]:
#################AdaBoost Classifier Algorithm##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [15]:
from sklearn.neural_network import MLPClassifier

In [16]:
a=MLPClassifier()

In [17]:
a=a.fit(X_train,y_train)

In [18]:
print(a.score(X_test,y_test)*10)

2.676056338028169

In [19]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur',
       'Gram', 'Groundnuts', 'Sessasum', 'Tea', 'Banana', 'Sugarcane',
       'Tobacco', 'Pepper', 'Chillies', 'Ginger', 'Coconut', 'Tumeric',
       'Bajra', 'Maize', 'Cotton', 'Potato'],
      dtype='object')

In [20]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur'])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Tea'])
Crop10=pd.DataFrame(f['Banana'])
Crop11=pd.DataFrame(f['Sugarcane'])
Crop12=pd.DataFrame(f['Tobacco'])
Crop13=pd.DataFrame(f['Pepper'])
Crop14=pd.DataFrame(f['Chillies'])
Crop15=pd.DataFrame(f['Ginger'])
Crop16=pd.DataFrame(f['Coconut'])
Crop17=pd.DataFrame(f['Tumeric'])
Crop18=pd.DataFrame(f['Bajra'])
Crop19=pd.DataFrame(f['Maize'])
Crop20=pd.DataFrame(f['Cotton'])
Crop21=pd.DataFrame(f['Potato'])

In [21]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)
Parameteronet=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop21],axis=1)

In [22]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur',axis=1)
y4=Parameteroned['Tur']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Tea',axis=1)
y8=Parameteroneh['Tea']

X9=Parameteronei.drop('Banana',axis=1)
y9=Parameteronei['Banana']

X10=Parameteronej.drop('Sugarcane',axis=1)
y10=Parameteronej['Sugarcane']

X11=Parameteronek.drop('Tobacco',axis=1)
y11=Parameteronek['Tobacco']

X12=Parameteronel.drop('Pepper',axis=1)
y12=Parameteronel['Pepper']

X13=Parameteronem.drop('Chillies',axis=1)
y13=Parameteronem['Chillies']

X14=Parameteronen.drop('Ginger',axis=1)
y14=Parameteronen['Ginger']

X15=Parameteroneo.drop('Coconut',axis=1)
y15=Parameteroneo['Coconut']

X16=Parameteronep.drop('Tumeric',axis=1)
y16=Parameteronep['Tumeric']

X17=Parameteroneq.drop('Bajra',axis=1)
y17=Parameteroneq['Bajra']

X18=Parameteroner.drop('Maize',axis=1)
y18=Parameteroner['Maize']

X19=Parameterones.drop('Cotton',axis=1)
y19=Parameterones['Cotton']

X20=Parameteronet.drop('Potato',axis=1)
y20=Parameteronet['Potato']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)
X_train20, X_test20, y_train20, y_test20 = train_test_split(X20, y20, test_size=0.70,random_state=70)

In [25]:
from sklearn.neural_network import MLPClassifier

In [26]:
b=MLPClassifier()
c=MLPClassifier()
d=MLPClassifier()
e=MLPClassifier()
f=MLPClassifier()
g=MLPClassifier()
h=MLPClassifier()
i=MLPClassifier()
j=MLPClassifier()
k=MLPClassifier()
l=MLPClassifier()
m=MLPClassifier()
n=MLPClassifier()
o=MLPClassifier()
p=MLPClassifier()
q=MLPClassifier()
r=MLPClassifier()
s=MLPClassifier()
t=MLPClassifier()
u=MLPClassifier()

In [27]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)
t.fit(X_train19,y_train19)
u.fit(X_train20,y_train20)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [28]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)
print(t.score(X_test19,y_test19)*10)
print(u.score(X_test20,y_test20)*10)

3.380281690140845
1.5492957746478873
0.4225352112676056
0.8450704225352113
1.6901408450704225
0.18309859154929578
1.5492957746478873
0.23943661971830985
1.5492957746478873
0.7042253521126761
0.0
1.0
0.971830985915493
10.0
1.1267605633802817
1.0
0.0
0.0
0.0
0.0