In [47]:
import numpy as np
import pandas as pd

In [48]:
a=pd.read_csv('JK climate.csv')
b=pd.read_csv('JK Soil.csv')
c=pd.read_csv('JK_groundwater.csv')
d=pd.read_csv('JK_Fertilizers.csv')
e=pd.read_csv('JK Pesticides.csv')
f=pd.read_csv('JK Crop data.csv')

In [49]:
climate=pd.DataFrame(a['Rainfall'])

In [50]:
Soil=pd.DataFrame(b['Ph'])

In [51]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [52]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [53]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [54]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [55]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [56]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,1238,7.0,0.15,140,54,1894
1,1239,8.0,1.15,141,55,1895
2,1240,9.0,2.15,142,56,1896
3,1241,7.2,3.15,143,57,1897
4,1242,8.3,4.15,144,58,1898
5,1243,9.1,5.15,145,59,1899
6,1244,8.0,6.15,146,60,1900
7,1245,9.0,7.15,147,61,1901
8,1246,7.2,8.15,148,62,1902
9,1247,8.3,9.15,149,63,1903
10,1248,9.0,10.15,150,64,1904
11,1249,7.2,11.15,151,65,1905
12,1250,8.3,12.15,152,66,1906
13,1251,9.1,13.15,153,67,1907
14,1252,8.0,14.15,154,68,1908
15,1253,9.0,15.15,155,69,1909
16,1254,7.2,16.15,156,70,1910
17,1255,8.0,17.15,157,71,1911
18,1256,9.0,18.15,158,72,1912
19,1257,7.2,19.15,159,73,1913
20,1258,8.3,20.15,160,74,1914
21,1259,9.1,21.15,161,75,1915
22,1260,8.0,22.15,162,76,1916
23,1261,9.0,23.15,163,77,1917
24,1262,7.2,24.15,164,78,1918
25,1263,8.3,25.15,165,79,1919
26,1264,9.0,26.15,166,80,1920
27,1265,7.2,27.15,167,81,1921
28,1266,8.3,28.15,168,82,1922
29,1267,9.1,29.15,169,83,1923
...,...,...,...,...,...,...
71,1309,8.3,71.15,211,125,1965
72,1310,9.1,72.15,212,126,1966
73,1311,8.0,73.15,213,127,1967
74,1312,9.0,74.15,214,128,1968
75,1313,7.2,75.15,215,129,1969
76,1314,8.3,76.15,216,130,1970
77,1315,9.0,77.15,217,131,1971
78,1316,7.2,78.15,218,132,1972
79,1317,8.3,79.15,219,133,1973
80,1318,9.1,80.15,220,134,1974
81,1319,8.0,81.15,221,135,1975
82,1320,9.0,82.15,222,136,1976
83,1321,7.0,83.15,223,137,1977
84,1322,8.0,84.15,224,138,1978
85,1323,9.0,85.15,225,139,1979
86,1324,7.2,86.15,226,140,1980
87,1325,8.3,87.15,227,141,1981
88,1326,9.1,88.15,228,142,1982
89,1327,8.0,89.15,229,143,1983
90,1328,9.0,90.15,230,144,1765
91,1329,7.2,91.15,231,145,1745
92,1330,8.3,92.15,232,146,1845
93,1331,9.0,93.15,233,147,1809
94,1332,9.0,94.15,234,148,1810
95,1333,7.2,95.15,235,149,1811
96,1334,8.3,96.15,236,150,1812
97,1335,9.1,97.15,237,151,1813
98,1336,8.0,98.15,238,152,1814
99,1337,9.0,99.15,239,153,1815
100,1338,7.2,100.15,240,154,1816

In [57]:
#################AdaBoost Classifier Algorithm##################

In [58]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [61]:
from sklearn.ensemble import RandomForestClassifier

In [62]:
a=RandomForestClassifier()

In [63]:
a=a.fit(X_train,y_train)

In [64]:
print(a.score(X_test,y_test)*10)

0.0

In [65]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Small Millets', 'Gram',
       'Sessasum', 'Sugarcane', 'Chillies', 'Ginger', 'Tumeric', 'Bajra',
       'Maize', 'Potato', 'Wheat', 'Other Pulses', 'Barley'],
      dtype='object')

In [66]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Small Millets'])
Crop4=pd.DataFrame(f['Gram'])
Crop5=pd.DataFrame(f['Sessasum'])
Crop6=pd.DataFrame(f['Sugarcane'])
Crop7=pd.DataFrame(f['Chillies'])
Crop8=pd.DataFrame(f['Ginger'])
Crop9=pd.DataFrame(f['Tumeric'])
Crop10=pd.DataFrame(f['Bajra'])
Crop11=pd.DataFrame(f['Maize'])
Crop12=pd.DataFrame(f['Potato'])
Crop13=pd.DataFrame(f['Wheat'])
Crop14=pd.DataFrame(f['Other Pulses'])
Crop15=pd.DataFrame(f['Barley'])

In [67]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)

In [68]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Small Millets',axis=1)
y2=Parameteroneb['Small Millets']

X3=Parameteronec.drop('Gram',axis=1)
y3=Parameteronec['Gram']

X4=Parameteroned.drop('Sessasum',axis=1)
y4=Parameteroned['Sessasum']

X5=Parameteronee.drop('Sugarcane',axis=1)
y5=Parameteronee['Sugarcane']

X6=Parameteronef.drop('Chillies',axis=1)
y6=Parameteronef['Chillies']

X7=Parameteroneg.drop('Ginger',axis=1)
y7=Parameteroneg['Ginger']

X8=Parameteroneh.drop('Tumeric',axis=1)
y8=Parameteroneh['Tumeric']

X9=Parameteronei.drop('Bajra',axis=1)
y9=Parameteronei['Bajra']

X10=Parameteronej.drop('Maize',axis=1)
y10=Parameteronej['Maize']

X11=Parameteronek.drop('Potato',axis=1)
y11=Parameteronek['Potato']

X12=Parameteronel.drop('Wheat',axis=1)
y12=Parameteronel['Wheat']

X13=Parameteronem.drop('Other Pulses',axis=1)
y13=Parameteronem['Other Pulses']

X14=Parameteronen.drop('Barley',axis=1)
y14=Parameteronen['Barley']

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)

In [71]:
from sklearn.ensemble import RandomForestClassifier

In [72]:
b=RandomForestClassifier()
c=RandomForestClassifier()
d=RandomForestClassifier()
e=RandomForestClassifier()
f=RandomForestClassifier()
g=RandomForestClassifier()
h=RandomForestClassifier()
i=RandomForestClassifier()
j=RandomForestClassifier()
k=RandomForestClassifier()
l=RandomForestClassifier()
m=RandomForestClassifier()
n=RandomForestClassifier()
o=RandomForestClassifier()

In [73]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [74]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)

0.0
10.0
0.0
0.0
0.0
1.0
10.0
1.0
0.0
0.14084507042253522
0.0
0.0
0.0
0.0