In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('RJ climate.csv')
b=pd.read_csv('RJ_Soil.csv')
c=pd.read_csv('RJ_groundwater.csv')
d=pd.read_csv('RJ_Fertilizers.csv')
e=pd.read_csv('RJ_Pesticides.csv')
f=pd.read_csv('RJ Crop data .csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,6101,8.5,0.01,1709,2278,1426
1,5475,8.6,1.01,1710,2279,1427
2,6228,8.7,2.01,1711,2280,1428
3,7192,8.8,3.01,1712,2281,1429
4,9560,9.0,4.01,1713,2282,1430
5,4695,8.6,5.01,1714,2283,1431
6,8742,8.7,6.01,1715,2284,1432
7,7459,8.8,7.01,1716,2285,1433
8,6427,8.5,8.01,1717,2286,1434
9,5974,8.6,9.01,1718,2287,1435
10,6924,8.7,10.01,1719,2288,1436
11,7692,8.8,11.01,1720,2289,1437
12,5317,9.0,12.01,1721,2290,1438
13,9889,8.6,13.01,1722,2291,1439
14,8498,8.7,14.01,1723,2292,1440
15,7151,8.7,15.01,1724,2293,1441
16,5613,8.8,16.01,1725,2294,1442
17,7247,9.0,17.01,1726,2295,1443
18,4961,8.6,18.01,1727,2296,1444
19,4137,8.7,19.01,1728,2297,1445
20,6511,8.8,20.01,1729,2298,1446
21,5047,8.5,21.01,1730,2299,1447
22,10192,8.6,22.01,1731,2300,1448
23,6942,8.7,23.01,1732,2301,1449
24,8496,8.8,24.01,1733,2302,1450
25,9587,9.0,25.01,1734,2303,1451
26,9947,8.6,26.01,1735,2304,1452
27,7781,8.7,27.01,1736,2305,1453
28,7162,8.8,28.01,1737,2306,1454
29,5885,9.0,29.01,1738,2307,1455
...,...,...,...,...,...,...
71,4927,8.6,71.01,1780,2349,1497
72,6373,8.7,72.01,1781,2350,1498
73,6553,8.8,73.01,1782,2351,1499
74,8998,9.0,74.01,1783,2352,1500
75,7623,8.6,75.01,1784,2353,1501
76,9278,8.7,76.01,1785,2354,1502
77,7409,8.8,77.01,1786,2355,1503
78,6465,9.0,78.01,1787,2356,1504
79,5644,8.6,79.01,1788,2357,1505
80,4717,8.7,80.01,1789,2358,1506
81,7768,8.8,81.01,1790,2359,1507
82,3090,8.5,82.01,1791,2360,1508
83,6493,8.6,83.01,1792,2361,1509
84,7050,8.7,84.01,1793,2362,1510
85,6315,8.8,85.01,1794,2363,1511
86,7772,9.0,86.01,1795,2364,1512
87,6382,8.6,87.01,1796,2365,1513
88,6179,8.7,88.01,1797,2366,1514
89,5310,8.7,89.01,1798,2367,1515
90,7859,8.8,90.01,1799,2368,2167
91,8432,9.0,91.01,1800,2369,2168
92,8245,8.6,92.01,1801,2370,2169
93,9014,8.7,93.01,1802,2371,2170
94,6683,8.8,94.01,1803,2372,2171
95,6918,8.5,95.01,1804,2373,2172
96,8734,8.6,96.01,1805,2374,2173
97,8735,8.7,97.01,1806,2375,2174
98,4204,8.7,98.01,1807,2376,2175
99,9053,8.8,99.01,1808,2377,2176
100,6918,9.0,100.01,1809,2378,2177

In [11]:
#################AdaBoost Classifier Algorithm##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [15]:
from sklearn import svm

In [16]:
a=svm.SVC()

In [17]:
a=a.fit(X_train,y_train)

In [18]:
print(a.score(X_test,y_test)*10)

0.0

In [19]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Small Millets'])
Crop4=pd.DataFrame(f['Tur '])
Crop5=pd.DataFrame(f['Gram'])
Crop6=pd.DataFrame(f['Groundnuts'])
Crop7=pd.DataFrame(f['Sessasum'])
Crop8=pd.DataFrame(f['Sugarcane'])
Crop9=pd.DataFrame(f['Tobacco'])
Crop10=pd.DataFrame(f['Chillies'])
Crop11=pd.DataFrame(f['Ginger'])
Crop12=pd.DataFrame(f['Tumeric'])
Crop13=pd.DataFrame(f['Bajra'])
Crop14=pd.DataFrame(f['Maize'])
Crop15=pd.DataFrame(f['Cotton'])
Crop16=pd.DataFrame(f['Potato'])
Crop17=pd.DataFrame(f['Wheat'])
Crop18=pd.DataFrame(f['Other Pulses'])
Crop19=pd.DataFrame(f['Barley'])

In [20]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)

In [21]:

X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Small Millets',axis=1)
y2=Parameteroneb['Small Millets']

X3=Parameteronec.drop('Tur ',axis=1)
y3=Parameteronec['Tur ']

X4=Parameteroned.drop('Gram',axis=1)
y4=Parameteroned['Gram']

X5=Parameteronee.drop('Groundnuts',axis=1)
y5=Parameteronee['Groundnuts']

X6=Parameteronef.drop('Sessasum',axis=1)
y6=Parameteronef['Sessasum']

X7=Parameteroneg.drop('Sugarcane',axis=1)
y7=Parameteroneg['Sugarcane']

X8=Parameteroneh.drop('Tobacco',axis=1)
y8=Parameteroneh['Tobacco']

X9=Parameteronei.drop('Chillies',axis=1)
y9=Parameteronei['Chillies']

X10=Parameteronej.drop('Ginger',axis=1)
y10=Parameteronej['Ginger']

X11=Parameteronek.drop('Tumeric',axis=1)
y11=Parameteronek['Tumeric']

X12=Parameteronel.drop('Bajra',axis=1)
y12=Parameteronel['Bajra']

X13=Parameteronem.drop('Maize',axis=1)
y13=Parameteronem['Maize']

X14=Parameteronen.drop( 'Cotton',axis=1)
y14=Parameteronen[ 'Cotton']

X15=Parameteroneo.drop('Potato',axis=1)
y15=Parameteroneo['Potato']

X16=Parameteronep.drop('Wheat',axis=1)
y16=Parameteronep['Wheat']

X17=Parameteroneq.drop('Other Pulses',axis=1)
y17=Parameteroneq['Other Pulses']

X18=Parameteroner.drop('Barley',axis=1)
y18=Parameteroner['Barley']

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)

In [24]:
from sklearn import svm

In [25]:
b=svm.SVC()
c=svm.SVC()
d=svm.SVC()
e=svm.SVC()
f=svm.SVC()
g=svm.SVC()
h=svm.SVC()
i=svm.SVC()
j=svm.SVC()
k=svm.SVC()
l=svm.SVC()
m=svm.SVC()
n=svm.SVC()
o=svm.SVC()
p=svm.SVC()
q=svm.SVC()
r=svm.SVC()
s=svm.SVC()

In [26]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9))
print(k.score(X_test10,y_test10))
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.8873239436619719
0.8873239436619719
0.8873239436619719
0.0
0.0
0.0
0.0
0.0
0.0
0.0