In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('climate Test1.csv')
b=pd.read_csv('Soil Test1.csv')
c=pd.read_csv('groundwater Test1.csv')
d=pd.read_csv('Fertilizers Test1.csv')
e=pd.read_csv('Pesticides Test1.csv')
f=pd.read_csv('Crop data Test1.csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,8125,8.6,30.01,1739,2308,1456
1,3697,8.7,31.01,1740,2309,1457
2,7455,8.8,32.01,1741,2310,1458
3,6229,8.5,33.01,1742,2311,1459
4,7685,8.6,34.01,1743,2312,1460
5,8841,8.7,35.01,1744,2313,1461
6,9628,8.8,36.01,1745,2314,1462
7,7498,9.0,37.01,1746,2315,1463
8,8031,8.6,38.01,1747,2316,1464
9,8692,8.7,39.01,1748,2317,1465
10,6146,8.7,40.01,1749,2318,1466
11,8480,8.8,41.01,1750,2319,1467
12,6527,9.0,42.01,1751,2320,1468
13,6636,8.6,43.01,1752,2321,1469
14,6312,8.7,44.01,1753,2322,1470
15,4369,8.8,45.01,1754,2323,1471
16,5060,8.5,46.01,1755,2324,1472
17,7701,8.6,47.01,1756,2325,1473
18,5375,8.7,48.01,1757,2326,1474
19,6374,8.8,49.01,1758,2327,1475
20,7671,9.0,50.01,1759,2328,1476
21,8735,8.7,51.01,1760,2329,1477
22,4204,8.8,52.01,1761,2330,1478
23,9053,9.0,53.01,1762,2331,1479
24,6486,8.6,54.01,1763,2332,1480
25,8346,8.7,55.01,1764,2333,1481
26,7865,8.8,56.01,1765,2334,1482
27,9719,8.5,57.01,1766,2335,1483
28,8980,8.6,58.01,1767,2336,1484
29,6181,8.7,59.01,1768,2337,1485
30,5625,8.8,60.01,1769,2338,1486

In [11]:
#################Ada Boost Classifier##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
Parameterone.columns

Index([' Rainfall', 'Ph', 'Rise (Depth of Water)', 'NPK(tonnes)',
       'MALATHION(QTY)(kg)', 'Rice(kg/hectare)'],
      dtype='object')

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
a=RandomForestClassifier()

In [18]:
a=a.fit(X_train,y_train)

In [19]:
print(a.score(X_test,y_test)*10)

0.0

In [20]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Small Millets', 'Tur ', 'Gram',
       'Groundnuts', 'Sessasum', 'Sugarcane', 'Tobacco', 'Chillies', 'Ginger',
       'Tumeric', 'Bajra', 'Maize', 'Cotton', 'Potato', 'Wheat',
       'Other Pulses', 'Barley'],
      dtype='object')

In [21]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Small Millets'])
Crop4=pd.DataFrame(f['Tur '])
Crop5=pd.DataFrame(f['Gram'])
Crop6=pd.DataFrame(f['Groundnuts'])
Crop7=pd.DataFrame(f['Sessasum'])
Crop8=pd.DataFrame(f['Sugarcane'])
Crop9=pd.DataFrame(f['Tobacco'])
Crop10=pd.DataFrame(f['Chillies'])
Crop11=pd.DataFrame(f['Ginger'])
Crop12=pd.DataFrame(f['Tumeric'])
Crop13=pd.DataFrame(f['Bajra'])
Crop14=pd.DataFrame(f['Maize'])
Crop15=pd.DataFrame(f['Cotton'])
Crop16=pd.DataFrame(f['Potato'])
Crop17=pd.DataFrame(f['Wheat'])
Crop18=pd.DataFrame(f['Other Pulses'])
Crop19=pd.DataFrame(f['Barley'])

In [22]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)

In [23]:
X2=Parameteronea.drop('Jowar',axis=1)
y2=Parameteronea['Jowar']

X3=Parameteroneb.drop('Small Millets',axis=1)
y3=Parameteroneb['Small Millets']

X4=Parameteronec.drop('Tur ',axis=1)
y4=Parameteronec['Tur ']

X5=Parameteroned.drop('Gram',axis=1)
y5=Parameteroned['Gram']

X6=Parameteronee.drop('Groundnuts',axis=1)
y6=Parameteronee['Groundnuts']

X7=Parameteronef.drop('Sessasum',axis=1)
y7=Parameteronef['Sessasum']

X8=Parameteroneg.drop('Sugarcane',axis=1)
y8=Parameteroneg['Sugarcane']

X9=Parameteroneh.drop('Tobacco',axis=1)
y9=Parameteroneh['Tobacco']

X10=Parameteronei.drop('Chillies',axis=1)
y10=Parameteronei['Chillies']

X11=Parameteronej.drop('Ginger',axis=1)
y11=Parameteronej['Ginger']

X12=Parameteronek.drop('Tumeric',axis=1)
y12=Parameteronek['Tumeric']

X13=Parameteronel.drop('Bajra',axis=1)
y13=Parameteronel['Bajra']

X14=Parameteronem.drop('Maize',axis=1)
y14=Parameteronem['Maize']

X15=Parameteronen.drop( 'Cotton',axis=1)
y15=Parameteronen[ 'Cotton']

X16=Parameteroneo.drop('Potato',axis=1)
y16=Parameteroneo['Potato']

X17=Parameteronep.drop('Wheat',axis=1)
y17=Parameteronep['Wheat']

X18=Parameteroneq.drop('Other Pulses',axis=1)
y18=Parameteroneq['Other Pulses']

X19=Parameteroner.drop('Barley',axis=1)
y19=Parameteroner['Barley']

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)

In [26]:
from sklearn.ensemble import RandomForestClassifier

In [27]:
b=RandomForestClassifier()
c=RandomForestClassifier()
d=RandomForestClassifier()
e=RandomForestClassifier()
f=RandomForestClassifier()
g=RandomForestClassifier()
h=RandomForestClassifier()
i=RandomForestClassifier()
j=RandomForestClassifier()
k=RandomForestClassifier()
l=RandomForestClassifier()
m=RandomForestClassifier()
n=RandomForestClassifier()
o=RandomForestClassifier()
p=RandomForestClassifier()
q=RandomForestClassifier()
r=RandomForestClassifier()
s=RandomForestClassifier()

In [28]:
b.fit(X_train2,y_train2)
c.fit(X_train3,y_train3)
d.fit(X_train4,y_train4)
e.fit(X_train5,y_train5)
f.fit(X_train6,y_train6)
g.fit(X_train7,y_train7)
h.fit(X_train8,y_train8)
i.fit(X_train9,y_train9)
j.fit(X_train10,y_train10)
k.fit(X_train11,y_train11)
l.fit(X_train12,y_train12)
m.fit(X_train13,y_train13)
n.fit(X_train14,y_train14)
o.fit(X_train15,y_train15)
p.fit(X_train16,y_train16)
q.fit(X_train17,y_train17)
r.fit(X_train18,y_train18)
s.fit(X_train19,y_train19)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [29]:
print(b.score(X_test2,y_test2)*10)
print(c.score(X_test3,y_test3)*10)
print(d.score(X_test4,y_test4)*10)
print(e.score(X_test5,y_test5)*10)
print(f.score(X_test6,y_test6))
print(g.score(X_test7,y_test7)*10)
print(h.score(X_test8,y_test8))
print(i.score(X_test9,y_test9))
print(j.score(X_test10,y_test10))
print(k.score(X_test11,y_test11))
print(l.score(X_test12,y_test12))
print(m.score(X_test13,y_test13))
print(n.score(X_test14,y_test14)*10)
print(o.score(X_test15,y_test15)*10)
print(p.score(X_test16,y_test16))
print(q.score(X_test17,y_test17)*10)
print(r.score(X_test18,y_test18)*10)
print(s.score(X_test19,y_test19)*10)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0