In [33]:
import numpy as np
import pandas as pd

In [34]:
a=pd.read_csv('MA climate.csv')
b=pd.read_csv('MA_Soil.csv')
c=pd.read_csv('MA_groundwater.csv')
d=pd.read_csv('MA_Fertilizers.csv')
e=pd.read_csv('MA Pesticides.csv')
f=pd.read_csv('MA Crop data.csv')

In [35]:
climate=pd.DataFrame(a['Rainfall'])

In [36]:
Soil=pd.DataFrame(b['Ph'])

In [37]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [38]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [39]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [40]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [41]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [42]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,4981,7.5,0.05,2134,2254,1478
1,6093,7.6,0.05,2135,950,1789
2,6750,7.7,0.05,2136,5673,1678
3,6200,8.0,0.05,2137,7643,1378
4,6740,8.1,0.05,2138,7644,1678
5,5774,8.2,0.05,2139,7645,1679
6,6722,9.0,0.05,2140,7646,1680
7,7163,9.3,0.05,2141,7647,1681
8,7247,7.6,0.05,2142,7648,1682
9,6331,7.7,0.05,2143,7649,1683
10,7894,8.1,0.05,2144,7650,1684
11,9199,8.2,0.05,2145,7651,1685
12,9324,8.3,0.05,2146,7652,1686
13,10044,8.4,0.05,2147,7653,1687
14,7955,8.5,0.05,2148,7654,1688
15,6480,7.7,0.05,2149,7655,1689
16,5800,8.0,0.05,2150,7656,1690
17,7091,8.1,0.05,2151,7657,1691
18,9953,8.2,0.05,2152,7658,1692
19,5581,9.0,0.05,2153,7659,1693
20,6948,9.3,0.05,2154,7660,1694
21,5813,7.6,0.05,2155,7661,1695
22,7181,7.7,0.05,2156,7662,1696
23,8500,8.1,0.05,2157,7663,1697
24,8622,8.2,0.05,2158,7664,1698
25,5811,8.3,0.05,2159,7665,1699
26,9258,8.4,0.05,2160,7666,1700
27,7593,7.6,0.05,2161,7667,1701
28,8040,7.7,0.05,2162,7668,1702
29,7928,8.0,0.05,2163,7669,1703
...,...,...,...,...,...,...
71,7828,9.3,0.05,3219,7681,1702
72,5937,7.6,0.05,3220,7682,1703
73,8170,7.7,0.05,3221,7683,1704
74,7479,8.1,0.05,3222,879,1705
75,6064,8.2,0.05,3223,880,1706
76,7543,8.3,0.05,3224,881,1707
77,7841,8.4,0.05,3225,882,1708
78,8694,7.6,0.05,3226,883,1709
79,6854,7.7,0.05,3227,884,1678
80,6634,8.0,0.05,3228,885,1711
81,6191,8.1,0.05,3229,886,1712
82,5521,8.2,0.05,3230,887,1713
83,5662,9.0,0.05,3231,888,1714
84,8133,9.3,0.05,3232,889,1715
85,9413,7.6,0.05,3233,890,1705
86,11284,7.7,0.05,3234,891,1706
87,8143,8.1,0.05,3235,892,1707
88,7826,8.2,0.05,3236,893,1708
89,7731,8.3,0.05,3237,894,1478
90,9389,8.4,0.05,3238,895,1789
91,6678,8.5,0.05,3239,896,1678
92,4900,7.7,0.05,3240,897,1378
93,8056,7.7,0.05,3241,898,1678
94,7866,8.1,0.05,3242,880,1679
95,5470,8.2,0.05,3243,881,1680
96,7248,8.3,0.05,3244,882,1681
97,7249,8.4,0.05,3245,883,1682
98,11284,8.5,0.05,3246,884,1683
99,7251,9.3,0.05,3247,885,1684
100,7252,9.0,0.05,3248,886,1685

In [43]:
#################AdaBoost Classifier Algorithm##################

In [44]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [47]:
from sklearn.linear_model import SGDClassifier

In [48]:
a=SGDClassifier()

In [49]:
a=a.fit(X_train,y_train)

In [50]:
print(a.score(X_test,y_test)*10)

0.0

In [51]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur',
       'Gram', 'Groundnuts', 'Sessasum', 'Banana', 'Sugarcane', 'Tobacco',
       'Coconut', 'Bajra', 'Maize', 'Cotton', 'Potato', 'Wheat',
       'Other Pulses', 'Mesta', 'Barley'],
      dtype='object')

In [52]:
Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur'])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Tobacco'])
Crop12=pd.DataFrame(f['Coconut'])
Crop13=pd.DataFrame(f['Bajra'])
Crop14=pd.DataFrame(f['Maize'])
Crop15=pd.DataFrame(f['Cotton'])
Crop16=pd.DataFrame(f['Potato'])
Crop17=pd.DataFrame(f['Wheat'])
Crop18=pd.DataFrame(f['Other Pulses'])
Crop19=pd.DataFrame(f['Mesta'])
Crop20=pd.DataFrame(f['Barley'])

In [53]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)

In [54]:
X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur',axis=1)
y4=Parameteroned['Tur']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Tobacco',axis=1)
y10=Parameteronej['Tobacco']

X11=Parameteronek.drop('Coconut',axis=1)
y11=Parameteronek['Coconut']

X12=Parameteronel.drop('Bajra',axis=1)
y12=Parameteronel['Bajra']

X13=Parameteronem.drop('Maize',axis=1)
y13=Parameteronem['Maize']

X14=Parameteronen.drop('Cotton',axis=1)
y14=Parameteronen['Cotton']

X15=Parameteroneo.drop('Potato',axis=1)
y15=Parameteroneo['Potato']

X16=Parameteronep.drop('Wheat',axis=1)
y16=Parameteronep['Wheat']

X17=Parameteroneq.drop('Other Pulses',axis=1)
y17=Parameteroneq['Other Pulses']

X18=Parameteroner.drop('Mesta',axis=1)
y18=Parameteroner['Mesta']

X19=Parameterones.drop('Barley',axis=1)
y19=Parameterones['Barley']

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)

In [57]:
from sklearn.linear_model import SGDClassifier

In [58]:
b=SGDClassifier()
c=SGDClassifier()
d=SGDClassifier()
e=SGDClassifier()
f=SGDClassifier()
g=SGDClassifier()
h=SGDClassifier()
i=SGDClassifier()
j=SGDClassifier()
k=SGDClassifier()
l=SGDClassifier()
m=SGDClassifier()
n=SGDClassifier()
o=SGDClassifier()
p=SGDClassifier()
q=SGDClassifier()
r=SGDClassifier()
s=SGDClassifier()
t=SGDClassifier()

In [59]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)
t.fit(X_train19,y_train19)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [60]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)
print(t.score(X_test19,y_test19)*10)

10.0
0.0
0.0
0.28169014084507044
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0