In [12]:
import numpy as np
import pandas as pd

In [13]:
a=pd.read_csv('climate Test1.csv')
b=pd.read_csv('Soil Test1.csv')
c=pd.read_csv('groundwater Test1.csv')
d=pd.read_csv('Fertilizers Test1.csv')
e=pd.read_csv('Pesticides Test1.csv')
f=pd.read_csv('Crop data Test1.csv')

In [14]:
climate=pd.DataFrame(a[' Rainfall'])

In [15]:
Soil=pd.DataFrame(b['Ph'])

In [16]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [17]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [18]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [19]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [20]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [21]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,9419,7.6,0.16,1556,12345,2467
1,7608,7.6,0.18,1597,14567,2180
2,8980,8.5,0.17,1639,11235,2083
3,13078,8.5,0.16,1680,12345,2156
4,9674,7.6,0.11,1680,14567,2245
5,14305,7.6,0.18,1514,11235,2245
6,12504,8.5,0.17,1556,12345,2467
7,9252,8.5,0.16,1597,14567,2180
8,9862,7.6,0.17,1639,11235,2083
9,8488,7.6,0.16,1680,12345,2156
10,11428,8.5,0.11,1639,14567,2245
11,12419,8.5,0.18,1680,11235,2467
12,10311,7.6,0.17,1514,12345,2180
13,9689,7.6,0.16,1639,11235,2083
14,9984,7.6,0.18,1680,12345,2467
15,6439,7.6,0.17,1514,14567,2180
16,7138,8.5,0.16,1556,11235,2083
17,10265,8.5,0.11,1597,12345,2156
18,8206,7.6,0.18,1639,14567,2245
19,10334,7.6,0.17,1680,11235,2245
20,11803,8.5,0.16,1639,12345,2467
21,14086,8.5,0.18,1680,14567,2180
22,7556,7.6,0.17,1514,11235,2083
23,11409,7.6,0.16,1556,12345,2156
24,8194,8.5,0.11,1639,14567,2245
25,11802,8.5,0.18,1680,11235,2467
26,9360,8.5,0.17,1514,12345,2245
27,8349,7.6,0.16,1514,14567,2467
28,10798,7.6,0.17,1556,11235,2180
29,6030,8.5,0.16,1597,12345,2083
30,14994,8.5,0.11,1639,14567,2156

In [22]:
#################AdaBoost Classifier Algorithm##################

X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

from sklearn.ensemble import ExtraTreesClassifier

a=ExtraTreesClassifier()

a=a.fit(X_train,y_train)

print(a.score(X_test,y_test)*10)

Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Small Millets'])
Crop4=pd.DataFrame(f['Tur '])
Crop5=pd.DataFrame(f['Gram'])
Crop6=pd.DataFrame(f['Groundnuts'])
Crop7=pd.DataFrame(f['Sessasum'])
Crop8=pd.DataFrame(f['Banana'])
Crop9=pd.DataFrame(f['Sugarcane'])
Crop10=pd.DataFrame(f['Tobacco'])
Crop11=pd.DataFrame(f['Chillies'])
Crop12=pd.DataFrame(f['Ginger'])
Crop13=pd.DataFrame(f['Tumeric'])
Crop14=pd.DataFrame(f['Bajra'])
Crop15=pd.DataFrame(f['Maize'])
Crop16=pd.DataFrame(f['Potato'])
Crop17=pd.DataFrame(f['Wheat'])
Crop18=pd.DataFrame(f['Other Pulses'])
Crop19=pd.DataFrame(f['Barley'])

Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)

f.columns

X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Small Millets',axis=1)
y2=Parameteroneb['Small Millets']

X3=Parameteronec.drop('Tur ',axis=1)
y3=Parameteronec['Tur ']

X4=Parameteroned.drop('Gram',axis=1)
y4=Parameteroned['Gram']

X5=Parameteronee.drop('Groundnuts',axis=1)
y5=Parameteronee['Groundnuts']

X6=Parameteronef.drop('Sessasum',axis=1)
y6=Parameteronef['Sessasum']

X7=Parameteroneg.drop('Banana',axis=1)
y7=Parameteroneg['Banana']

X8=Parameteroneh.drop('Sugarcane',axis=1)
y8=Parameteroneh['Sugarcane']

X9=Parameteronei.drop('Tobacco',axis=1)
y9=Parameteronei['Tobacco']

X10=Parameteronej.drop('Chillies',axis=1)
y10=Parameteronej['Chillies']

X11=Parameteronek.drop('Ginger',axis=1)
y11=Parameteronek['Ginger']

X12=Parameteronel.drop('Tumeric',axis=1)
y12=Parameteronel['Tumeric']

X13=Parameteronem.drop('Bajra',axis=1)
y13=Parameteronem['Bajra']

X14=Parameteronen.drop('Maize',axis=1)
y14=Parameteronen['Maize']

X15=Parameteroneo.drop('Potato',axis=1)
y15=Parameteroneo['Potato']

X16=Parameteronep.drop('Wheat',axis=1)
y16=Parameteronep['Wheat']

X17=Parameteroneq.drop('Other Pulses',axis=1)
y17=Parameteroneq['Other Pulses']

X18=Parameteroner.drop('Barley',axis=1)
y18=Parameteroner['Barley']

from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)


from sklearn.ensemble import AdaBoostClassifier

b=AdaBoostClassifier()
c=AdaBoostClassifier()
d=AdaBoostClassifier()
e=AdaBoostClassifier()
f=AdaBoostClassifier()
g=AdaBoostClassifier()
h=AdaBoostClassifier()
i=AdaBoostClassifier()
j=AdaBoostClassifier()
k=AdaBoostClassifier()
l=AdaBoostClassifier()
m=AdaBoostClassifier()
n=AdaBoostClassifier()
o=AdaBoostClassifier()
p=AdaBoostClassifier()
q=AdaBoostClassifier()
r=AdaBoostClassifier()
s=AdaBoostClassifier()

b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)

print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)

2.2727272727272725
1.8181818181818183
1.8181818181818183
1.8181818181818183
1.8181818181818183
1.8181818181818183
0.18181818181818182
1.8181818181818183
0.09090909090909091
1.8181818181818183
4.545454545454545
0.18181818181818182
0.36363636363636365
0.18181818181818182
1.8181818181818183
1.8181818181818183
0.18181818181818182
1.8181818181818183
1.8181818181818183