In [33]:
import numpy as np
import pandas as pd

In [34]:
a=pd.read_csv('UK climate.csv')
b=pd.read_csv('UK Soil.csv')
c=pd.read_csv('UK_groundwater.csv')
d=pd.read_csv('UK_Fertilizers.csv')
e=pd.read_csv('UK Pesticides.csv')
f=pd.read_csv('UK Crop data.csv')

In [35]:
climate=pd.DataFrame(a['Rainfall'])

In [36]:
Soil=pd.DataFrame(b['Ph'])

In [37]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [38]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [39]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [40]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [41]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [42]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,170809,6,0.83,215,1527,1996
1,170810,8,0.81,216,1528,1997
2,170811,7,0.82,217,1529,1998
3,170812,6,0.80,218,1530,1999
4,170813,6,0.84,219,1531,2000
5,170814,7,0.82,220,1532,2001
6,170815,6,0.79,221,1533,2002
7,170816,8,0.82,222,1534,2003
8,170817,7,0.80,223,1535,2004
9,170818,6,0.84,224,1536,2005
10,170819,6,0.82,225,1537,2006
11,170820,7,0.79,226,1538,2007
12,170821,6,0.81,227,1539,2008
13,170822,8,0.82,228,1540,2009
14,170823,7,0.80,229,1541,2010
15,170824,6,0.84,230,1542,2011
16,170825,6,0.82,231,1543,2012
17,170826,7,0.79,232,1544,2013
18,170827,6,0.82,233,1545,2014
19,170828,8,0.80,234,1546,2015
20,170829,7,0.84,235,1547,2016
21,170830,6,0.80,236,1548,2017
22,170831,6,0.84,237,1549,2018
23,170832,6,0.82,238,1550,2019
24,170833,6,0.79,239,1551,2020
25,170834,7,0.82,240,1552,2002
26,320123,6,0.80,241,1553,2003
27,320123,8,0.84,242,1554,2004
28,320123,7,0.82,243,1555,2005
29,320123,6,0.79,244,1556,2006
...,...,...,...,...,...,...
71,320123,7,0.84,286,1598,2009
72,320123,6,0.82,287,1599,2010
73,320123,8,0.79,288,1600,2011
74,320123,7,0.82,289,1601,2012
75,320123,6,0.80,290,1602,2013
76,320123,6,0.84,291,1603,2014
77,320123,7,0.82,292,1604,2010
78,320123,6,0.79,293,1605,2011
79,320123,8,0.81,294,1606,2012
80,320123,7,0.82,295,1607,2013
81,320123,6,0.80,296,1608,2014
82,320123,6,0.84,297,1609,2015
83,320123,7,0.82,298,1610,2016
84,320123,6,0.79,299,1611,2017
85,240143,8,0.82,300,1612,2018
86,320123,7,0.80,301,1613,2019
87,320123,6,0.84,302,1614,2020
88,320123,6,0.80,303,1615,2021
89,320123,7,0.84,304,1616,2022
90,320123,6,0.82,305,1617,2034
91,320123,8,0.79,306,1618,2212
92,240143,7,0.82,307,1619,2634
93,240144,6,0.80,308,1620,2124
94,240145,6,0.84,309,1621,1998
95,240146,7,0.82,310,1622,1999
96,240147,6,0.79,311,1623,2000
97,240148,8,0.81,312,1624,2001
98,240149,7,0.82,313,1625,2002
99,240150,6,0.80,314,1626,2022
100,240151,6,0.84,297,1627,2034

In [43]:
#################AdaBoost Classifier Algorithm##################

In [44]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [47]:
from sklearn.ensemble import ExtraTreesClassifier

In [48]:
a=ExtraTreesClassifier()

In [49]:
a=a.fit(X_train,y_train)

In [50]:
print(a.score(X_test,y_test)*10)

0.14084507042253522

In [51]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Ragi', 'Small Millets', 'Tur', 'Gram',
       'Groundnuts', 'Sessasum', 'Sugarcane', 'Chillies', 'Ginger', 'Tumeric',
       'Maize', 'Potato', 'Wheat', 'Other Pulses', 'Barley'],
      dtype='object')

In [52]:
Crop2=pd.DataFrame(f['Ragi'])
Crop3=pd.DataFrame(f['Small Millets'])
Crop4=pd.DataFrame(f['Tur'])
Crop5=pd.DataFrame(f['Gram'])
Crop6=pd.DataFrame(f['Groundnuts'])
Crop7=pd.DataFrame(f['Sessasum'])
Crop8=pd.DataFrame(f['Sugarcane'])
Crop9=pd.DataFrame(f['Chillies'])
Crop10=pd.DataFrame(f['Ginger'])
Crop11=pd.DataFrame(f['Tumeric'])
Crop12=pd.DataFrame(f['Maize'])
Crop13=pd.DataFrame(f['Potato'])
Crop14=pd.DataFrame(f['Wheat'])
Crop15=pd.DataFrame(f['Other Pulses'])
Crop16=pd.DataFrame(f['Barley'])

In [53]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)

In [54]:
X1=Parameteronea.drop('Ragi',axis=1)
y1=Parameteronea['Ragi']

X2=Parameteroneb.drop('Small Millets',axis=1)
y2=Parameteroneb['Small Millets']

X3=Parameteronec.drop('Tur',axis=1)
y3=Parameteronec['Tur']

X4=Parameteroned.drop('Gram',axis=1)
y4=Parameteroned['Gram']

X5=Parameteronee.drop('Groundnuts',axis=1)
y5=Parameteronee['Groundnuts']

X6=Parameteronef.drop('Sessasum',axis=1)
y6=Parameteronef['Sessasum']

X7=Parameteroneg.drop('Sugarcane',axis=1)
y7=Parameteroneg['Sugarcane']

X8=Parameteroneh.drop('Chillies',axis=1)
y8=Parameteroneh['Chillies']

X9=Parameteronei.drop('Ginger',axis=1)
y9=Parameteronei['Ginger']

X10=Parameteronej.drop('Tumeric',axis=1)
y10=Parameteronej['Tumeric']

X11=Parameteronek.drop('Maize',axis=1)
y11=Parameteronek['Maize']

X12=Parameteronel.drop('Potato',axis=1)
y12=Parameteronel['Potato']

X13=Parameteronem.drop('Wheat',axis=1)
y13=Parameteronem['Wheat']

X14=Parameteronen.drop('Other Pulses',axis=1)
y14=Parameteronen['Other Pulses']

X15=Parameteroneo.drop('Barley',axis=1)
y15=Parameteroneo['Barley']

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)

In [57]:
from sklearn.ensemble import ExtraTreesClassifier

In [58]:
b=ExtraTreesClassifier()
c=ExtraTreesClassifier()
d=ExtraTreesClassifier()
e=ExtraTreesClassifier()
f=ExtraTreesClassifier()
g=ExtraTreesClassifier()
h=ExtraTreesClassifier()
i=ExtraTreesClassifier()
j=ExtraTreesClassifier()
k=ExtraTreesClassifier()
l=ExtraTreesClassifier()
m=ExtraTreesClassifier()
n=ExtraTreesClassifier()
o=ExtraTreesClassifier()
p=ExtraTreesClassifier()

In [59]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [60]:
print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)

0.14084507042253522
0.14084507042253522
0.14084507042253522
0.14084507042253522
10.0
0.014084507042253521
0.14084507042253522
0.014084507042253521
0.14084507042253522
0.5633802816901409
0.014084507042253521
0.014084507042253521
0.014084507042253521
0.14084507042253522
0.14084507042253522