In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('climate Test1.csv')
b=pd.read_csv('Soil Test1.csv')
c=pd.read_csv('groundwater Test1.csv')
d=pd.read_csv('Fertilizers Test1.csv')
e=pd.read_csv('Pesticides Test1.csv')
f=pd.read_csv('Crop data Test1.csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,14520,7.5,0.65,630,1197,1170
1,12442,6.8,0.65,631,1198,1170
2,13558,6.8,0.65,632,1199,1170
3,13587,6.9,0.65,633,1200,1170
4,13131,7.1,0.65,634,1201,1170
5,11892,7.5,0.65,635,1202,1170
6,14827,6.8,0.65,636,1203,1170
7,15924,6.9,0.65,637,1204,1170
8,11770,7.1,0.65,638,1205,1170
9,14846,7.5,0.65,639,1206,1170
10,15532,6.8,0.65,640,1207,1173
11,13511,6.9,0.65,641,1208,1173
12,20817,7.1,0.65,642,1209,1173
13,10233,7.5,0.65,643,1210,1173
14,13287,6.8,0.65,644,1211,1173
15,14228,6.9,0.65,645,1212,1173
16,10098,7.0,0.65,646,1213,1173
17,9714,7.5,0.65,647,1214,1173
18,13485,6.8,0.65,648,1215,1173
19,11686,6.9,0.65,649,1216,1173
20,11097,7.1,0.65,650,1217,1173
21,14430,7.5,0.65,651,1218,1173
22,15492,6.8,0.65,652,1219,1173
23,11851,6.9,0.65,653,1220,1173
24,14467,7.1,0.65,654,1221,1173
25,8212,7.5,0.65,655,1222,1173
26,14478,6.8,0.65,656,1223,1173
27,11480,6.9,0.65,657,1224,1173
28,15592,7.1,0.65,658,1225,1173
29,11935,7.5,0.65,659,1226,1173
30,8744,6.8,0.65,660,1227,1173

In [11]:
#################AdaBoost Classifier Algorithm##################

X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

from sklearn.gaussian_process import GaussianProcessClassifier

a=GaussianProcessClassifier()

a=a.fit(X_train,y_train)

print(a.score(X_test,y_test)*10)



Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur '])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Maize'])
Crop12=pd.DataFrame(f['Potato'])
Crop13=pd.DataFrame(f['Wheat'])
Crop14=pd.DataFrame(f['Other Pulses'])
Crop15=pd.DataFrame(f['Mesta'])
Crop16=pd.DataFrame(f['Coconut'])
Crop17=pd.DataFrame(f['Barley'])

Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)


X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur ',axis=1)
y4=Parameteroned['Tur ']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Maize',axis=1)
y10=Parameteronej['Maize']

X11=Parameteronek.drop('Potato',axis=1)
y11=Parameteronek['Potato']

X12=Parameteronel.drop('Wheat',axis=1)
y12=Parameteronel['Wheat']

X13=Parameteronem.drop('Other Pulses',axis=1)
y13=Parameteronem['Other Pulses']

X14=Parameteronen.drop('Mesta',axis=1)
y14=Parameteronen['Mesta']

X15=Parameteroneo.drop('Coconut',axis=1)
y15=Parameteroneo['Coconut']

X16=Parameteronep.drop('Barley',axis=1)
y16=Parameteronep['Barley']

from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)



from sklearn.gaussian_process import GaussianProcessClassifier

b=GaussianProcessClassifier()
c=GaussianProcessClassifier()
d=GaussianProcessClassifier()
e=GaussianProcessClassifier()
f=GaussianProcessClassifier()
g=GaussianProcessClassifier()
h=GaussianProcessClassifier()
i=GaussianProcessClassifier()
j=GaussianProcessClassifier()
k=GaussianProcessClassifier()
l=GaussianProcessClassifier()
m=GaussianProcessClassifier()
n=GaussianProcessClassifier()
o=GaussianProcessClassifier()
p=GaussianProcessClassifier()
q=GaussianProcessClassifier()



b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)


print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))

9.09090909090909
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0