In [70]:
import numpy as np
import pandas as pd

In [71]:
a=pd.read_csv('HR_climate.csv')
b=pd.read_csv('HR_Soil.csv')
c=pd.read_csv('HR_groundwater.csv')
d=pd.read_csv('HR_Fertilizers.csv')
e=pd.read_csv('HR_Pesticides_.csv')
f=pd.read_csv('HR_Crop_data.csv')

In [72]:
climate=pd.DataFrame(a['Rainfall'])

In [73]:
Soil=pd.DataFrame(b['Ph'])

In [74]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [75]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [76]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [77]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [78]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [79]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,3716,6.6,0.59,1340,3439,2156
1,4760,6.7,0.59,1341,3440,2245
2,5512,6.8,0.59,1342,3441,2245
3,5835,8.0,0.59,1343,3442,2467
4,6510,8.1,0.59,1344,3443,2245
5,5698,8.5,0.59,1345,3444,2467
6,6435,6.7,0.59,1346,3445,2180
7,5131,6.8,0.59,1347,3446,2083
8,4100,8.0,0.59,1348,3447,2156
9,3364,8.1,0.59,1349,3448,2245
10,5443,6.8,0.59,1350,3449,2245
11,5115,8.0,0.59,1351,3450,2467
12,4683,8.1,0.59,1352,3451,2180
13,9976,8.5,0.59,1353,3452,2083
14,5196,6.7,0.59,1354,3453,2156
15,5841,6.8,0.59,1355,3454,2245
16,5496,8.0,0.59,1356,3455,2467
17,5244,6.6,0.59,1357,3456,2180
18,2698,6.7,0.59,1358,3457,2083
19,3061,6.8,0.59,1359,3458,2467
20,3780,8.0,0.59,1360,3459,2156
21,3836,8.1,0.59,1361,3460,2245
22,7995,8.5,0.59,1362,3461,2245
23,4278,6.7,0.59,1363,3462,2467
24,5033,6.8,0.59,1364,3463,2180
25,7290,8.0,0.59,1365,3464,2083
26,4263,8.1,0.59,1366,3465,2156
27,5236,6.8,0.59,1367,3466,2245
28,6495,8.0,0.59,1368,3467,2467
29,5505,8.1,0.59,1369,3468,2180
...,...,...,...,...,...,...
71,4125,8.1,0.59,1411,3510,2467
72,4602,8.5,0.59,1412,3511,2180
73,5995,6.7,0.59,1413,3512,2083
74,6182,6.8,0.59,1414,3513,2156
75,8223,8.0,0.59,1415,3514,2245
76,7022,6.6,0.59,1416,3515,2467
77,7273,6.7,0.59,1417,3516,2180
78,7700,6.8,0.59,1418,3517,2083
79,3394,8.0,0.59,1419,3518,2467
80,4410,8.1,0.59,1420,3519,2467
81,6177,8.5,0.59,1421,3520,2245
82,4066,6.7,0.59,1422,3521,2467
83,6219,6.8,0.59,1423,3522,2180
84,5766,8.0,0.59,1424,3523,2083
85,6708,8.1,0.59,1425,3524,2156
86,3927,6.8,0.59,1426,3525,2245
87,5203,8.0,0.59,1427,3526,2245
88,7418,8.1,0.59,1428,3527,2467
89,4159,8.5,0.59,1429,3528,2180
90,6725,6.7,0.59,1430,3529,2083
91,5344,6.8,0.59,1431,3530,2156
92,4690,8.0,0.59,1432,3531,2245
93,5810,8.1,0.59,1433,3532,2245
94,3493,8.5,0.59,1434,3533,2245
95,4371,6.7,0.59,1435,3534,2467
96,3852,6.8,0.59,1436,3535,2180
97,6182,8.0,0.59,1437,3536,2083
98,8223,8.1,0.59,1438,3537,2156
99,7022,6.8,0.59,1439,3538,2245
100,7273,8.0,0.59,1440,3539,2467

In [80]:
#################AdaBoost Classifier Algorithm##################

In [81]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [84]:
from sklearn.ensemble import AdaBoostClassifier

In [85]:
a=AdaBoostClassifier()

In [86]:
a=a.fit(X_train,y_train)

In [87]:
print(a.score(X_test,y_test)*10)

1.6901408450704225

In [88]:
Crop2=pd.DataFrame(f['Tur'])
Crop3=pd.DataFrame(f['Gram'])
Crop4=pd.DataFrame(f['Groundnuts'])
Crop5=pd.DataFrame(f['Sessasum'])
Crop6=pd.DataFrame(f['Sugarcane'])
Crop7=pd.DataFrame(f['Chillies'])
Crop8=pd.DataFrame(f['Ginger'])
Crop9=pd.DataFrame(f['Tumeric'])
Crop10=pd.DataFrame(f['Maize'])
Crop11=pd.DataFrame(f['Potato'])
Crop12=pd.DataFrame(f['Wheat'])
Crop13=pd.DataFrame(f['Other Pulses'])
Crop14=pd.DataFrame(f['Barley'])
Crop15=pd.DataFrame(f['Jowar'])
Crop16=pd.DataFrame(f['Bajra'])
Crop17=pd.DataFrame(f['Cotton'])

In [89]:
Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)

In [90]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Tur', 'Gram', 'Groundnuts', 'Sessasum',
       'Sugarcane', 'Chillies', 'Ginger', 'Tumeric', 'Maize', 'Potato',
       'Wheat', 'Other Pulses', 'Barley', 'Jowar', 'Bajra', 'Cotton'],
      dtype='object')

In [91]:
X1=Parameteronea.drop('Tur',axis=1)
y1=Parameteronea['Tur']

X2=Parameteroneb.drop('Gram',axis=1)
y2=Parameteroneb['Gram']

X3=Parameteronec.drop('Groundnuts',axis=1)
y3=Parameteronec['Groundnuts']

X4=Parameteroned.drop('Sessasum',axis=1)
y4=Parameteroned['Sessasum']

X5=Parameteronee.drop('Sugarcane',axis=1)
y5=Parameteronee['Sugarcane']

X6=Parameteronef.drop('Chillies',axis=1)
y6=Parameteronef['Chillies']

X7=Parameteroneg.drop('Ginger',axis=1)
y7=Parameteroneg['Ginger']

X8=Parameteroneh.drop('Tumeric',axis=1)
y8=Parameteroneh['Tumeric']

X9=Parameteronei.drop('Maize',axis=1)
y9=Parameteronei['Maize']

X10=Parameteronej.drop('Potato',axis=1)
y10=Parameteronej['Potato']

X11=Parameteronek.drop('Wheat',axis=1)
y11=Parameteronek['Wheat']

X12=Parameteronel.drop('Other Pulses',axis=1)
y12=Parameteronel['Other Pulses']

X13=Parameteronem.drop('Barley',axis=1)
y13=Parameteronem['Barley']

X14=Parameteronen.drop('Jowar',axis=1)
y14=Parameteronen['Jowar']

X15=Parameteroneo.drop('Bajra',axis=1)
y15=Parameteroneo['Bajra']

X16=Parameteronep.drop('Cotton',axis=1)
y16=Parameteronep['Cotton']

In [92]:
from sklearn.model_selection import train_test_split

In [93]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)

In [94]:
from sklearn.ensemble import AdaBoostClassifier

In [95]:
b=AdaBoostClassifier()
c=AdaBoostClassifier()
d=AdaBoostClassifier()
e=AdaBoostClassifier()
f=AdaBoostClassifier()
g=AdaBoostClassifier()
h=AdaBoostClassifier()
i=AdaBoostClassifier()
j=AdaBoostClassifier()
k=AdaBoostClassifier()
l=AdaBoostClassifier()
m=AdaBoostClassifier()
n=AdaBoostClassifier()
o=AdaBoostClassifier()
p=AdaBoostClassifier()
q=AdaBoostClassifier()

In [96]:
b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [98]:
print(b.score(X_test1,y_test1))
print(c.score(X_test2,y_test2))
print(d.score(X_test3,y_test3))
print(e.score(X_test4,y_test4))
print(f.score(X_test5,y_test5))
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7))
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9))
print(k.score(X_test10,y_test10))
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14))
print(p.score(X_test15,y_test15))
print(q.score(X_test16,y_test16))

0.16901408450704225
0.16901408450704225
0.16901408450704225
0.16901408450704225
0.16901408450704225
0.16901408450704225
0.16901408450704225
0.16901408450704225
0.16901408450704225
0.29577464788732394
0.16901408450704225
0.5070422535211268
0.16901408450704225
0.16901408450704225
0.16901408450704225
0.16901408450704225