In [1]:
import numpy as np
import pandas as pd

In [2]:
a=pd.read_csv('climate Test1.csv')
b=pd.read_csv('Soil Test1.csv')
c=pd.read_csv('groundwater Test1.csv')
d=pd.read_csv('Fertilizers Test1.csv')
e=pd.read_csv('Pesticides Test1.csv')
f=pd.read_csv('Crop data Test1.csv')

In [3]:
climate=pd.DataFrame(a[' Rainfall'])

In [4]:
Soil=pd.DataFrame(b['Ph'])

In [5]:
Water=pd.DataFrame(c['Rise (Depth of Water)'])

In [6]:
Fertilizer=pd.DataFrame(d['NPK(tonnes)'])

In [7]:
Pesticides=pd.DataFrame(e['MALATHION(QTY)(kg)'])

In [8]:
Crop=pd.DataFrame(f['Rice(kg/hectare)'])

In [9]:
Parameterone=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop],axis=1)

In [10]:
Parameterone

,Rainfall,Ph,Rise (Depth of Water),NPK(tonnes),MALATHION(QTY)(kg),Rice(kg/hectare)
0,17283,6.3,30.16,2547,1486,2488
1,16673,6.2,31.16,2548,1487,2489
2,13232,6.3,32.16,2549,1488,2490
3,15373,6.6,33.16,2550,1489,2491
4,15543,6.7,34.16,2551,1490,2492
5,11514,6.2,35.16,2552,1491,2493
6,13599,6.3,36.16,2553,1492,2494
7,18185,6.6,37.16,2554,1493,2495
8,12117,6.7,38.16,2555,1494,2496
9,12270,6.1,39.16,2556,1495,2497
10,17168,6.2,40.16,2557,1496,2498
11,13398,6.3,41.16,2558,1497,2499
12,15420,6.6,42.16,2559,1498,2500
13,12911,6.7,43.16,2560,1499,2501
14,13079,6.2,44.16,2561,1500,2502
15,12561,6.3,45.16,2562,1501,2503
16,12982,6.6,46.16,2563,1502,2504
17,12131,6.3,47.16,2564,1503,2505
18,15848,6.6,48.16,2565,1504,2506
19,15608,6.7,49.16,2566,1505,2507
20,14257,6.2,50.16,2567,1506,2508
21,17177,6.3,51.16,2568,1507,2509
22,21823,6.6,52.16,2569,1508,2510
23,12643,6.7,53.16,2570,1509,2511
24,17507,6.1,54.16,2571,1510,2512
25,16581,6.2,55.16,2572,1511,2513
26,14076,6.3,56.16,2573,1512,2514
27,11677,6.6,57.16,2574,1513,2515
28,17113,6.7,58.16,2575,1514,2516
29,18233,6.7,59.16,2576,1515,2517
30,10832,6.2,60.16,2577,1516,2518

In [11]:
#################Ada Boost Classifier##################

In [12]:
X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

In [13]:
Parameterone.columns

Index([' Rainfall', 'Ph', 'Rise (Depth of Water)', 'NPK(tonnes)',
       'MALATHION(QTY)(kg)', 'Rice(kg/hectare)'],
      dtype='object')

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

In [16]:
from sklearn.ensemble import AdaBoostClassifier

In [17]:
a=AdaBoostClassifier()

In [18]:
a=a.fit(X_train,y_train)

In [19]:
print(a.score(X_test,y_test)*10)

0.0

In [20]:
f.columns

Index(['Year', 'Rice(kg/hectare)', 'Jowar', 'Ragi', 'Small Millets', 'Tur ',
       'Gram', 'Groundnuts', 'Sessasum', 'Banana', 'Sugarcane', 'Tobacco',
       'Bajra', 'Maize', 'Potato', 'Wheat', 'Other Pulses', 'Barley', 'Jute ',
       'Mesta', 'Coconut', 'Tea'],
      dtype='object')

In [23]:
#################AdaBoost Classifier Algorithm##################

X=Parameterone.drop('Rice(kg/hectare)',axis=1)
y=Parameterone['Rice(kg/hectare)']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.70,random_state=70)

from sklearn.gaussian_process import GaussianProcessClassifier

a=GaussianProcessClassifier()

a=a.fit(X_train,y_train)

print(a.score(X_test,y_test)*10)

Crop2=pd.DataFrame(f['Jowar'])
Crop3=pd.DataFrame(f['Ragi'])
Crop4=pd.DataFrame(f['Small Millets'])
Crop5=pd.DataFrame(f['Tur '])
Crop6=pd.DataFrame(f['Gram'])
Crop7=pd.DataFrame(f['Groundnuts'])
Crop8=pd.DataFrame(f['Sessasum'])
Crop9=pd.DataFrame(f['Banana'])
Crop10=pd.DataFrame(f['Sugarcane'])
Crop11=pd.DataFrame(f['Tobacco'])
Crop12=pd.DataFrame(f['Bajra'])
Crop13=pd.DataFrame(f['Maize'])
Crop14=pd.DataFrame(f['Potato'])
Crop15=pd.DataFrame(f['Wheat'])
Crop16=pd.DataFrame(f['Other Pulses'])
Crop17=pd.DataFrame(f['Barley'])
Crop18=pd.DataFrame(f['Jute '])
Crop19=pd.DataFrame(f['Mesta'])
Crop20=pd.DataFrame(f['Coconut'])
Crop21=pd.DataFrame(f['Tea'])

Parameteronea=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop2],axis=1)
Parameteroneb=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop3],axis=1)
Parameteronec=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop4],axis=1)
Parameteroned=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop5],axis=1)
Parameteronee=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop6],axis=1)
Parameteronef=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop7],axis=1)
Parameteroneg=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop8],axis=1)
Parameteroneh=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop9],axis=1)
Parameteronei=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop10],axis=1)
Parameteronej=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop11],axis=1)
Parameteronek=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop12],axis=1)
Parameteronel=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop13],axis=1)
Parameteronem=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop14],axis=1)
Parameteronen=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop15],axis=1)
Parameteroneo=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop16],axis=1)
Parameteronep=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop17],axis=1)
Parameteroneq=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop18],axis=1)
Parameteroner=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop19],axis=1)
Parameterones=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop20],axis=1)
Parameteronet=pd.concat([climate,Soil,Water,Fertilizer,Pesticides,Crop21],axis=1)

X1=Parameteronea.drop('Jowar',axis=1)
y1=Parameteronea['Jowar']

X2=Parameteroneb.drop('Ragi',axis=1)
y2=Parameteroneb['Ragi']

X3=Parameteronec.drop('Small Millets',axis=1)
y3=Parameteronec['Small Millets']

X4=Parameteroned.drop('Tur ',axis=1)
y4=Parameteroned['Tur ']

X5=Parameteronee.drop('Gram',axis=1)
y5=Parameteronee['Gram']

X6=Parameteronef.drop('Groundnuts',axis=1)
y6=Parameteronef['Groundnuts']

X7=Parameteroneg.drop('Sessasum',axis=1)
y7=Parameteroneg['Sessasum']

X8=Parameteroneh.drop('Banana',axis=1)
y8=Parameteroneh['Banana']

X9=Parameteronei.drop('Sugarcane',axis=1)
y9=Parameteronei['Sugarcane']

X10=Parameteronej.drop('Tobacco',axis=1)
y10=Parameteronej['Tobacco']

X11=Parameteronek.drop('Bajra',axis=1)
y11=Parameteronek['Bajra']

X12=Parameteronel.drop('Maize',axis=1)
y12=Parameteronel['Maize']

X13=Parameteronem.drop('Potato',axis=1)
y13=Parameteronem['Potato']

X14=Parameteronen.drop('Wheat',axis=1)
y14=Parameteronen['Wheat']

X15=Parameteroneo.drop('Other Pulses',axis=1)
y15=Parameteroneo['Other Pulses']

X16=Parameteronep.drop('Barley',axis=1)
y16=Parameteronep['Barley']

X17=Parameteroneq.drop('Jute ',axis=1)
y17=Parameteroneq['Jute ']

X18=Parameteroner.drop('Mesta',axis=1)
y18=Parameteroner['Mesta']

X19=Parameterones.drop('Coconut',axis=1)
y19=Parameterones['Coconut']

X20=Parameteronet.drop('Tea',axis=1)
y20=Parameteronet['Tea']

from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.70,random_state=70)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.70,random_state=70)
X_train3, X_test3, y_train3, y_test3 = train_test_split(X3, y3, test_size=0.70,random_state=70)
X_train4, X_test4, y_train4, y_test4 = train_test_split(X4, y4, test_size=0.70,random_state=70)
X_train5, X_test5, y_train5, y_test5 = train_test_split(X5, y5, test_size=0.70,random_state=70)
X_train6, X_test6, y_train6, y_test6 = train_test_split(X6, y6, test_size=0.70,random_state=70)
X_train7, X_test7, y_train7, y_test7 = train_test_split(X7, y7, test_size=0.70,random_state=70)
X_train8, X_test8, y_train8, y_test8 = train_test_split(X8, y8, test_size=0.70,random_state=70)
X_train9, X_test9, y_train9, y_test9 = train_test_split(X9, y9, test_size=0.70,random_state=70)
X_train10, X_test10, y_train10, y_test10 = train_test_split(X10, y10, test_size=0.70,random_state=70)
X_train11, X_test11, y_train11, y_test11 = train_test_split(X11, y11, test_size=0.70,random_state=70)
X_train12, X_test12, y_train12, y_test12 = train_test_split(X12, y12, test_size=0.70,random_state=70)
X_train13, X_test13, y_train13, y_test13 = train_test_split(X13, y13, test_size=0.70,random_state=70)
X_train14, X_test14, y_train14, y_test14 = train_test_split(X14, y14, test_size=0.70,random_state=70)
X_train15, X_test15, y_train15, y_test15 = train_test_split(X15, y15, test_size=0.70,random_state=70)
X_train16, X_test16, y_train16, y_test16 = train_test_split(X16, y16, test_size=0.70,random_state=70)
X_train17, X_test17, y_train17, y_test17 = train_test_split(X17, y17, test_size=0.70,random_state=70)
X_train18, X_test18, y_train18, y_test18 = train_test_split(X18, y18, test_size=0.70,random_state=70)
X_train19, X_test19, y_train19, y_test19 = train_test_split(X19, y19, test_size=0.70,random_state=70)
X_train20, X_test20, y_train20, y_test20 = train_test_split(X20, y20, test_size=0.70,random_state=70)

from sklearn.gaussian_process import GaussianProcessClassifier


b=GaussianProcessClassifier()
c=GaussianProcessClassifier()
d=GaussianProcessClassifier()
e=GaussianProcessClassifier()
f=GaussianProcessClassifier()
g=GaussianProcessClassifier()
h=GaussianProcessClassifier()
i=GaussianProcessClassifier()
j=GaussianProcessClassifier()
k=GaussianProcessClassifier()
l=GaussianProcessClassifier()
m=GaussianProcessClassifier()
n=GaussianProcessClassifier()
o=GaussianProcessClassifier()
p=GaussianProcessClassifier()
q=GaussianProcessClassifier()
r=GaussianProcessClassifier()
s=GaussianProcessClassifier()
t=GaussianProcessClassifier()
u=GaussianProcessClassifier()

b.fit(X_train1,y_train1)
c.fit(X_train2,y_train2)
d.fit(X_train3,y_train3)
e.fit(X_train4,y_train4)
f.fit(X_train5,y_train5)
g.fit(X_train6,y_train6)
h.fit(X_train7,y_train7)
i.fit(X_train8,y_train8)
j.fit(X_train9,y_train9)
k.fit(X_train10,y_train10)
l.fit(X_train11,y_train11)
m.fit(X_train12,y_train12)
n.fit(X_train13,y_train13)
o.fit(X_train14,y_train14)
p.fit(X_train15,y_train15)
q.fit(X_train16,y_train16)
r.fit(X_train17,y_train17)
s.fit(X_train18,y_train18)
t.fit(X_train19,y_train19)
u.fit(X_train20,y_train20)

print(b.score(X_test1,y_test1)*10)
print(c.score(X_test2,y_test2)*10)
print(d.score(X_test3,y_test3)*10)
print(e.score(X_test4,y_test4)*10)
print(f.score(X_test5,y_test5)*10)
print(g.score(X_test6,y_test6))
print(h.score(X_test7,y_test7)*10)
print(i.score(X_test8,y_test8))
print(j.score(X_test9,y_test9)*10)
print(k.score(X_test10,y_test10)*10)
print(l.score(X_test11,y_test11))
print(m.score(X_test12,y_test12))
print(n.score(X_test13,y_test13))
print(o.score(X_test14,y_test14)*10)
print(p.score(X_test15,y_test15)*10)
print(q.score(X_test16,y_test16))
print(r.score(X_test17,y_test17)*10)
print(s.score(X_test18,y_test18)*10)
print(t.score(X_test19,y_test19)*10)
print(u.score(X_test20,y_test20)*10)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
10.0